### ISSUE TITLE
Click on alert button

### ISSUE THREAD

**Issue by 2inqui** [nalexn/ViewInspector#103]
Hi @nalexn  do you know if it is possible to click on an alert view button

```
struct ContentView: View {
    
    @State private var showingAlert = false

    var body: some View {
        Button("Show Alert") {
            showingAlert = true
        }
        .alert(isPresented: $showingAlert) {
            Alert(title: Text("Important message"), message: Text("Wear sunscreen"), dismissButton: .default(Text("Got it!")))
        }
    }

}
```

what I've tried

```
    func testClickOnAlertButton() throws {
        // Given
        let view = ContentView()
        ViewHosting.host(view: view)
        
        let button = try view.inspect()
            .find(ContentView.self)
            .find(text: "Got it!")
            
        print(button)
    }
```

How do I click on the Got it! button?

**Comment by nalexn** [comment]
Hey, I can see there is currently [no full support](https://github.com/nalexn/ViewInspector/blob/master/readiness.md#presenting-alerts) for inspecting the Alerts. I'll have a look if I can push it further

**Comment by 2inqui** [comment]
Thanks for the confirmation and thanks for the project it really helps to test some basic functionality of the UI.

**Comment by nalexn** [comment]
Sure! I'll re-open this ticket to serve as a reminder for myself and as a ref for others

**Comment by alexbasson** [comment]
Part of what's challenging about `Alert` is that, surprisingly, it isn't actually a `View`, i.e. it doesn't actually conform to the `View` protocol.

**Comment by nalexn** [comment]
The fact that `Alert` isn't a `View` is less of a problem, its structure is fully transparent and easy to access.
The problem is with the `.alert` modifier itself, as it does not store the `Alert` structure directly, and instead has the `transform` closure with several private SwiftUI types:

```swift
ModifiedContent<EmptyView, AlertTransformModifier<Key>>
  content: EmptyView = EmptyView()
  modifier: AlertTransformModifier<Key>
    transform: (inout Optional<Presentation>, ViewIdentity, CGRect) -> () = (Function)
```

I can see one way to approach it (but I'm not a big fan of this) is by adding a new `.alert2` function with the same API which would retain the `Alert` structure and show the `.alert` the normal way.

**Comment by nalexn** [comment]
I think having that in the toolbox is better than nothing, I just need to come up with the name for this replacement modifier. Open for suggestions.

**Comment by 2inqui** [comment]
I'm not sure if I understood correctly but you want to add a alert2 modifier that will have to be used within the real implementation? if so I don't believe that having a dependency to a Testing library in your project its a good idea.

**Comment by nalexn** [comment]
@2inqui yeah, at first I thought to make it part of the library, but quickly realized that making it a dependency for the main build target is a no-go for sure. So it'll be a small code snippet that would have to be added to the main build target, thus the name can be chosen by the user - either `alert2` or something else. Relatively small invasion to the source code for gaining testability

**Comment by nalexn** [comment]
The v0.7.6 added support for inspecting `Alert`. With a [few tweaks to the code](https://github.com/nalexn/ViewInspector/blob/master/guide.md#making-alert-inspectable), you should be able to access the Alert's buttons:

```swift
try sut.inspect().find(ViewType.AlertButton.self, containing: "Got it!").tap()
```
