### ISSUE TITLE
Missing debug information

### ISSUE THREAD

**Issue by PappBalazs** [nalexn/ViewInspector#114]
Hello there!

I just upgraded your library from 0.5.1 to 0.7.7

Let me attach 2 screenshots. Both have the same code, one is from 0.5.1 the other is from 0.7.7
As you can see in the debug window the "po" command (po buttonImage) worked nicely for the older version and it stopped working in the latest version. Now it says: "Execution was interrupted, reason: EXC-BAD_ACCESS".
Do you have any idea why?

Working 0.5.1
<img width="1211" alt="po_0 5 1" src="https://user-images.githubusercontent.com/5303043/121206073-746f1600-c878-11eb-8e7c-b197a34f505c.png">

Not working 0.7.7
<img width="1447" alt="po_0 7 7" src="https://user-images.githubusercontent.com/5303043/121206106-7cc75100-c878-11eb-906d-e0272c5e2ba2.png">

**Comment by nalexn** [comment]
What's quite a major upgrade (from 0.5.1 to 0.7.7) to easily tell you what are the changes causing this. I'll need you to either provide the essential part of the `WhatsNewView` you're testing, or try to localize the problem yourself by testing the image name in isolation. As far as I can see, the name is extracted correctly, so why do you need to `po` in this test anyways?

**Comment by PappBalazs** [comment]
This happens with all my custom views. Name is extracted correctly, and everything is working fine.
I have problem only when I want to use debug console to PO some view.

However I found the problem, I am not sure what we can do against this.
So in this example I try to `po buttonImage` and `Execution was interrupted, reason: EXC_BAD_ACCESS` occurs.

I am using `try view.inspect()` if I used `try? view.inspect()` it would work.

**Comment by patrickbdev** [comment]
@PappBalazs another solution is to wrap your expression in a `dump` i.e. `po dump(try screen.inspect())`.
This will however also produce `expression produced error: error: ...` at the end of the dump.
To prevent that you can also wrap it in a `do` i.e. `po do { dump(try screen.inspect()) }`.
I tested this with 0.8.1.
@PappBalazs are these solutions enough to close the issue?

**Comment by PappBalazs** [comment]
@patrickbdev Yes, both the optional and the do { try { catch }} work
