### ISSUE TITLE
MapAnnotation build error

### ISSUE THREAD

**Issue by iDevid** [nalexn/ViewInspector#116]
Hi all! Our CI is giving an error with the latest version of ViewInspector 0.8.0 during the build:
```
SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/SwiftUI/MapAnnotation.swift:38:25: value of optional type 'ViewType.MapAnnotation.`Type`?' must be unwrapped to a value of type 'ViewType.MapAnnotation.`Type`'
```

**Comment by nalexn** [comment]
Hey! Thanks for reporting! I'll have a look today

**Comment by nalexn** [comment]
This looks like an Xcode versioning problem. I'll download 12.4 to assure it compiles there.

**Comment by nalexn** [comment]
You should be good now (v0.8.1)

**Comment by iDevid** [comment]
Thank you for the fix!
