### ISSUE TITLE
GeometryReader size is always y0x0

### ISSUE THREAD

**Issue by JinSeiBeats** [nalexn/ViewInspector#117]
I'm trying to test a view with a GeometryReader in it. But the size always stays 0. 
```
   var body: some View {
        GeometryReader { geometry in
            let size = geometry.size
            if (geometry.size.width < iconBreakPoint) {
              // contentSmall 
            } else {
              // contenBig
            }
        }
    }
```

```
let view = ViewToTest()
             .frame(width: 200, height: 200)
             .inspect()
```
Even with the frame the geometry reader always reports no size.

**Comment by nalexn** [comment]
Hey @JinSeiBeats ,

Yeah, this is a limitation of the library - there is currently no way to make `GeometryReader` report any size except for `zero`
