### ISSUE TITLE
Build failure with ViewInspector as a dependency of a package test target

### ISSUE THREAD

**Issue by orchetect** [nalexn/ViewInspector#122]
When working in a Swift Package Manager package in Xcode, adding ViewInspector as a dependency to a test target causes Xcode to fail to build that target.

```swift
dependencies: [
    // ...
    .package(url: "https://github.com/nalexn/ViewInspector", from: "0.8.1")
    // ...
],

targets: [
    .target(name: "SomePackage")
    .testTarget(name: "SomePackageTests", 
                dependencies: ["SomePackage", "ViewInspector"])
]
```

```
2021-07-10 13:03:32.580245-0700 xctest[39418:4153616] The bundle "SomePackageTests" couldn’t be loaded. Try reinstalling the bundle.
2021-07-10 13:03:32.580493-0700 xctest[39418:4153616] (dlopen(/Users/user/Library/Developer/Xcode/DerivedData/SomePackage-djfuipmvqfvpwnaqapxukcuilgyy/Build/Products/Debug/SomePackageTests.xctest/Contents/MacOS/SomePackageTests, 265): Symbol not found: _$s7SwiftUI16PageTabViewStyleV16IndexDisplayModeVMn
  Referenced from: /Users/user/Library/Developer/Xcode/DerivedData/SomePackage-djfuipmvqfvpwnaqapxukcuilgyy/Build/Products/Debug/SomePackageTests.xctest/Contents/MacOS/SomePackageTests
  Expected in: /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
 in /Users/user/Library/Developer/Xcode/DerivedData/SomePackage-djfuipmvqfvpwnaqapxukcuilgyy/Build/Products/Debug/SomePackageTests.xctest/Contents/MacOS/SomePackageTests)
Program ended with exit code: 9
```

Additionally, Xcode's log shows this:

```
xctest (40165) encountered an error (Failed to request test plan from the initial test runner. (Underlying Error: The operation couldn’t be completed. (DTXProxyChannel error 1.)))
```

The strange thing is that, without ViewInspector, `import SwiftUI` builds and works fine in both normal targets and test targets. As soon as you add "ViewInspector" as a dependency to the test target in Package.swift, that test target fails to build.

I would love to do some unit testing of some SwiftUI components that my main target is emitting.

Thanks for any help on this.

**Comment by orchetect** [comment]
This is the only hint I could find when Googling:

https://stackoverflow.com/questions/34704388/xctest-error-the-bundle-couldn-t-be-loaded-try-reinstalling-the-bundle

I tried adding minimum OS requirements to the package (which I would like to avoid, as I want to support older OSes and only conditionally add SwiftUI components which has worked great until now that I am trying to add ViewInspector to the mix)

```swift
let package = Package(
    name: "SomePackage",
    platforms: [.macOS(.v10_15), .iOS(.v13), .watchOS(.v7)], // added just to test
    // ...
```

But the same build error was happening.

**Comment by patrickbdev** [comment]
@orchetect can you create a minimal example project and upload it?

**Comment by orchetect** [comment]
Here is a barebones Swift Package that replicates the issue.

[VITest.zip](https://github.com/nalexn/ViewInspector/files/6911893/VITest.zip)

The package has appropriate minimum OS requirements for importing SwiftUI.

Build succeeds, but running the unit test produces the following console error. None of the logs have any further detail.

```
2021-07-31 15:08:06.188862-0700 xctest[52974:2939557] The bundle “VITestTests” couldn’t be loaded. Try reinstalling the bundle.
2021-07-31 15:08:06.189185-0700 xctest[52974:2939557] (dlopen(/Users/user/Library/Developer/Xcode/DerivedData/VITest-avaaubwymiladhdlzlwlojfdziio/Build/Products/Debug/VITestTests.xctest/Contents/MacOS/VITestTests, 265): Symbol not found: _$s7SwiftUI16PageTabViewStyleV16IndexDisplayModeVMn
  Referenced from: /Users/user/Library/Developer/Xcode/DerivedData/VITest-avaaubwymiladhdlzlwlojfdziio/Build/Products/Debug/VITestTests.xctest/Contents/MacOS/VITestTests
  Expected in: /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
 in /Users/user/Library/Developer/Xcode/DerivedData/VITest-avaaubwymiladhdlzlwlojfdziio/Build/Products/Debug/VITestTests.xctest/Contents/MacOS/VITestTests)
Program ended with exit code: 83
```

**Comment by nalexn** [comment]
Hey, sorry for the late reaction.

I've just downloaded your sample project and ran tests in Xcode 13.1, no issues:

<img width="1072" alt="Screenshot 2021-11-25 at 16 40 04" src="https://user-images.githubusercontent.com/1594746/143451865-0c0edb6c-35b5-4cc1-9361-3c37bb0471e2.png">

I think clearing DerivedData and other standard tricks with Xcode would have resolved it for you. Let me know if this still does not work for you.

**Comment by orchetect** [comment]
Looks to be working for me as well in Xcode 13.1.
