### ISSUE TITLE
Simulate typing

### ISSUE THREAD

**Issue by SumoSimo** [nalexn/ViewInspector#123]
Hi there.

I'm wondering if it's possible to simulate typing in any sort of input field. As an example, it could be useful when testing that the entered credentials on a login form are correctly passed into the login flow that handles the network call.

Thanks!

**Comment by nalexn** [comment]
Hey,

There is an API for that, for example, for TextField and TextInput you can use setInput(...). For DatePicker there is select(date: ...), etc. API reference: https://github.com/nalexn/ViewInspector/blob/master/readiness.md

**Comment by SumoSimo** [comment]
Good to know! I'll make sure to use that reference the next time I go looking for something. Thanks!

**Comment by SumoSimo** [comment]
So I just tried using `setInput(...)` using two approaches. The first was without using `View.host(...)`, and the second was with `View.host(...)` using the more flexible option. In both cases, the `@State` property in my view wasn't updated.

Is this the intended behavior, or am I missing something?

**Comment by patrickbdev** [comment]
@SumoSimo have you [read this section? ](https://github.com/nalexn/ViewInspector/blob/master/guide.md#views-using-state-environment-or-environmentobject)
Observing properties like `@State` require some refactoring.

**Comment by SumoSimo** [comment]
@patrickbdev I have read that section. I tried the second approach and still saw the issue occur.

**Comment by patrickbdev** [comment]
@SumoSimo would you be able to upload a simple sample project?

**Comment by nalexn** [comment]
I consider this issue no longer relevant. Feel free to re-open
