### ISSUE TITLE
Support watchOS 

### ISSUE THREAD

**Issue by wiemerm** [nalexn/ViewInspector#125]
I can see that the resolution to #20 was to remove support for watchOS due to the lack of XCTest support when using Xcode 12.4 or earlier. However, since Xcode 12.5 we can now use XCTest with watchOS. Would like to see watchOS supported again.

**Comment by nalexn** [comment]
I'll look into this, thanks!

**Comment by nalexn** [comment]
I've created a branch [watchOS](https://github.com/nalexn/ViewInspector/tree/watchOS) for this ticket. Not an easy one, due to quite a poor API design for presenting new view controllers in WatchKit.

**Comment by nalexn** [comment]
watchOS support added in [v0.9.0](https://github.com/nalexn/ViewInspector/releases/tag/0.9.0)
