### ISSUE TITLE
Xcode 13 Beta 5 issues

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [nalexn/ViewInspector#128]
Looks like the latest Xcode release (today) broke some ViewInspector code. As far as I can tell it's isolated to things with a `label()` or `labelView()`. I might spend a little time trying to dig into *why*, but I figured I'd report it as an issue.

**Comment by patrickbdev** [comment]
I noticed that from beta 2 as well. It's difficult to say whether the change is a permanent one or something that will revert once GM is released.

**Comment by nalexn** [comment]
There are quite some inner changes in SwiftUI shipped with iOS 15 beta, I've just updated most part in [0.8.2](https://github.com/nalexn/ViewInspector/tree/0.8.2)

**Comment by gscalzo** [comment]
Any plan for releasing 0.8.2?
(Congrats and thank you very much for this awesome library!)

**Comment by nalexn** [comment]
Hey @gscalzo , it's coming, just need to brush up docs and wrap up the watchOS support

**Comment by nalexn** [comment]
This is now fixed in [v0.9.0](https://github.com/nalexn/ViewInspector/releases/tag/0.9.0)
