### ISSUE TITLE
failed - Search did not find a match. Possible blockers: RoundedRectangle

### ISSUE THREAD

**Issue by bukira** [nalexn/ViewInspector#133]
I am trying to find something, in this case its an alert, but same applies to buttons or text

try view.find(ViewType.AlertButton.self, containing: "Allow").tap()

I get the error 
"failed - Search did not find a match. Possible blockers: RoundedRectangle"

each view could be a different blocker, but always a blocker, how do I get around this ?

This seems to be the offending "RoundedRectangle" in this case

                    Text("OK")
                        .frame(minWidth: 0, maxWidth: .infinity)
                        .font(.mediumFont15)
                        .padding()
                        .foregroundColor(.primaryBlack)
                        .background(
                            RoundedRectangle(cornerRadius: 5.0)
                                .foregroundColor(.primaryWhite)
                                .frame(height: 45.0)
                                .cornerRadius(5.0).padding(40.0))

Is this just a red herring as when I comment out the "RoundedRectangle"

I get

"failed - Search did not find a match"

**Comment by bukira** [comment]
I think its a red herring, just not very helpful as to what the blocker means, 

try view.find(ViewType.Button.self, containing: "OK").tap()

This works and is able to find it, its the system alerts it couldn't find

**Comment by nalexn** [comment]
I bet `RoundedRectangle` isn't registered for search in ViewInspector, I'll double-check and fix it. It is not intended to show up as "blocker", usually "blockers" are the custom views that do not conform to `Inspectable`

**Comment by bukira** [comment]
Thank you very much for this and really helps me, how do I register "UIViewControllerRepresentable" as Inpsectable?

**Comment by nalexn** [comment]
Here is [an example](https://github.com/nalexn/ViewInspector/blob/master/Tests/ViewInspectorTests/SwiftUI/CustomViewTests.swift#L273)

**Comment by bukira** [comment]
awesome

**Comment by nalexn** [comment]
I consider this issue resolved. A promised fix for the `RoundedRectangle` being a blocker is deployed in [0.9.0](https://github.com/nalexn/ViewInspector/releases/tag/0.9.0)

**Comment by matis-schotte** [comment]
> I bet `RoundedRectangle` isn't registered for search in ViewInspector, I'll double-check and fix it. It is not intended to show up as "blocker", usually "blockers" are the custom views that do not conform to `Inspectable`

This is a _very_ important piece of information. Might I suggest adding it to the documentation?
Or did I just overlook it being already somewhere?
