### ISSUE TITLE
system alerts

### ISSUE THREAD

**Issue by bukira** [nalexn/ViewInspector#134]
How do I find system alerts to tap on them

I tried

let exp = sut.inspection.inspect(after: 0.1) { view in
 try view.find(ViewType.AlertButton.self, containing: "Allow").tap()
}

But it cant find this,

This alert is a system alert to allow push notifications

**Comment by nalexn** [comment]
Hey - the system alerts are not part of the app's main window hierarchy, they are presented in a separate one. In theory, you can access that hierarchy by finding the right window from `UIApplication` or `UIScene`, but I doubt Apple is using SwiftUI for system alerts, so you'll end up iterating over the UIKit views there.

**Comment by bukira** [comment]
Thanks, so basically. I just need to stop app during testing from presenting system alerts
