### ISSUE TITLE
No support for Shapes

### ISSUE THREAD

**Issue by nrivard** [nalexn/ViewInspector#14]
There is no current support for shapes: `Rectangle`, `Circle`, `Ellipse`, `Capsule`, `Path`, `RoundedRectangle`.

There is no current support for manipulated shapes: `TransformedShape`, `InsettableShape`, `OffsetShape`, `RotatedShape`, `ScaledShape`.

**Comment by nalexn** [comment]
Support for `Shape` is added in `v0.3.7`
