### ISSUE TITLE
Crash on Xcode13 not in Xcode12

### ISSUE THREAD

**Issue by pjcau** [nalexn/ViewInspector#141]
Hi All, 

I upated to Xcode13 and I have this error in the library

<img width="1678" alt="Screenshot 2021-10-04 at 10 45 25" src="https://user-images.githubusercontent.com/1088176/135821087-df03a35a-b0f3-4d8f-b0c3-38b9262fb75f.png">

Can you have news about the xcode13?

BR

J

**Comment by nalexn** [comment]
Hey, could you post the structure of the `ChannelsView`: which variables or property wrappers it has, exactly as they are declared in the view? You can skip the body of the view.

**Comment by pjcau** [comment]
OK, 

```

import SwiftUI

struct ChannelsView: View {
    @EnvironmentObject var viewModel: ChannelsViewModel
    @State var selectedModelChannel: Contents.Content? = nil
    @State var navigationViewIsActive: Bool = true {
        didSet {
            debugPrint("Home navigationViewIsActive is \(navigationViewIsActive)")
        }
    }

    let columns = [
        GridItem(.flexible(minimum: 50)),
    ]

    internal var didAppear: ((Self) -> Void)? // for ViewInspector testing purposes

    var body: some View {
        ...
    }
}

```

**Comment by pjcau** [comment]
Have you Newas

> Hey, could you post the structure of the `ChannelsView`: which variables or property wrappers it has, exactly as they are declared in the view? You can skip the body of the view.

Have you news? 

J

**Comment by nalexn** [comment]
Hey, I'm running short on free time, sorry. I'll get back to this issue shortly

**Comment by nalexn** [comment]
Hey, I tried to replicate the problem with the code you shared and could not get it to crash. Could you share a sample project where the issue can be reproduced?

**Comment by nalexn** [comment]
Closing this ticket, assuming you have resolved the issue. Feel free to re-open
