### ISSUE TITLE
breaking changes to alerts...

### ISSUE THREAD

**Issue by bukira** [nalexn/ViewInspector#142]
Since the breaking changes to the alert and sheet etc get an error when trying to test

This is my view code with both an Alert and a Sheet

        }.alertInspectable(isPresented: $viewModel.showAlert) {
            Alert(
                title: Text(viewModel.alertTitle()),
                message: Text(viewModel.alertMessage()),
                dismissButton: .default(
                    Text("OK"),
                    action: viewModel.dismissAlert
                )
            )
        }.sheetInspectable(isPresented: $viewModel.isShowingScanner, onDismiss: {
            viewModel.dismissScanner()
        }) {
            CodeScannerView(codeTypes: [.qr], simulatedData: "dGVzdEB0ZXN0LmNvbTpwYXNzd29yZA==", completion: viewModel.handleScan)
        }

When I try to test this as follows

                    let exp = sut.inspection.inspect { view in
                        let alert = try view.zStack().alert()
                        expect(try alert.title().string()).to(equal("error title"))
                        expect(try alert.message().string()).to(equal("error message"))
                        expect(try alert.primaryButton().style()).to(equal(.default))
                        try sut.inspect().find(ViewType.AlertButton.self, containing: "OK").tap()
                    }

I get an error

**Referencing instance method 'message()' on 'InspectableView' requires the types 'ViewType.Alert' and 'ViewType.ActionSheet' be equivalent**

This never happened previously 

I have used the new code in the docs for the breaking changes and used **alertInspectable** instead of **alert2** etc

Thanks

**Comment by Xidrovo** [comment]
Hey @bukira could you resolve this?, I'm in the same situation and don't know what to do

**Comment by bukira** [comment]
No I didn't, I think it was just the alert.message() that had the issue, so I just commented it out for now

**Comment by nalexn** [comment]
My apologies for the late response.

Short answer:

Just insert `.text()` after `.message()` for `Alert`

Long answer:

iOS 15 APIs have added `func alert` overloads that allow the message to be an arbitrary view, not just a `Text`.

So, while `message()` is defined for both `Alert` and `ActionSheet`, now they return views of different types: `ClassifiedView` and `Text` respectively. This is unfortunate that the compiler's error is rather misleading in this case, given the incorrect code when calling `string()` on a `ClassifiedView`.

Compare the inspection chains, given the Alert and ActionSheet have the same root:

```swift
let alert = try sut.alert()
let sheet = try sut.actionSheet()
XCTAssertEqual(try alert.message().text().string(), "Alert Message")
XCTAssertEqual(try sheet.message().string(), "Sheet Message")
```
