### ISSUE TITLE
'Cannot find 'XCTFail' in scope' when integrating with CocoaPods

### ISSUE THREAD

**Issue by MihaiDamian** [nalexn/ViewInspector#145]
When integrating via CocoPods I get the error 'Cannot find 'XCTFail' in scope' when ViewInspector is being built.

The Podfile looks like this:

```
platform :ios, '13.0'

project 'Demo.xcodeproj'

target 'DemoTests' do
	pod 'ViewInspector', '0.9.0'
end
```

The problem is that ENABLE_TESTING_SEARCH_PATHS is not set to YES in the ViewInspector target. I think you need something like this in your Podspec:

```
 s.pod_target_xcconfig = {
    'ENABLE_TESTING_SEARCH_PATHS' => 'YES',
 }
```

I'm using ViewInspector 0.9.0 and Xcode 13.

I attached a demo project that shows the problem.

[Demo.zip](https://github.com/nalexn/ViewInspector/files/7346429/Demo.zip)

**Comment by muzammil-triffort** [comment]
@MihaiDamian I am having the same issue. Have you found any solution for this?

**Comment by nalexn** [comment]
Thank you for reporting this!
I did update the `Podspec` for the next version, however, I'm confused why this was needed as `ENABLE_TESTING_SEARCH_PATHS` was set to `YES` in the 0.9.0

<img width="666" alt="Screenshot 2021-11-21 at 14 39 03" src="https://user-images.githubusercontent.com/1594746/142760428-b04641ba-5ad9-4bcc-9f57-1a2849ea12d9.png">

**Comment by nalexn** [comment]
Released with v0.9.1

**Comment by MihaiDamian** [comment]
@nalexn This issue is not fixed. ENABLE_TESTING_SEARCH_PATHS needs to be added to the Podspec. Settings in the library's project file are not preserved by Cocoapods.

**Comment by nalexn** [comment]
Gotcha, will be done for the next release. Sorry for not double-checking.
