### ISSUE TITLE
Question: How to check the Shape type

### ISSUE THREAD

**Issue by gedaiu** [nalexn/ViewInspector#158]
Is there a way to query all the shapes of certain type or check if a Shape view is of a certain type?

maybe something like this?

```
let elements = try subject
                        .inspect()
                        .findAll(ViewType.Shape.self, where: { shape in return shape.isCircle })

```
or

```
let elements = try subject
                        .inspect()
                        .findAll(ViewType.Circle.self, where: { _ in true })

```

**Comment by nalexn** [comment]
Hey, the way SwiftUI stores `Shape` views does not allow to reliably judge on its type, however, as a workaround you can try to compare the returned Shape's `path(in rect: CGRect)`.

**Comment by gedaiu** [comment]
hmmm... I actually want a component that based on it's state to render different shapes of the same size... not sure if `path(in rect: CGRect)` will work. But I think I can wrap the shapes in some other views and query those wrappers to check the right thing is happening
