### ISSUE TITLE
Weird error message for inspect call: 

### ISSUE THREAD

**Issue by gedaiu** [nalexn/ViewInspector#159]
When I try to inspect a view, I get this error message: 

anyView() found TestApp.AnnotationView instead of AnyView

```
let shape = try subject
                        .inspect()
                        .anyView()
                        .shape(0)
```

How should I interpret this error message, and how can I debug it?

**Comment by nalexn** [comment]
Hey, this message says there is apparently an `AnnotationView` in your hierarchy, and not the `AnyView`. If that's your custom view, extend it in the tests file with `Inspectable` conformance:

```swift
extension AnnotationView: Inspectable { }
```
and instead of `.anyView()` use `.view(AnnotationView.self)` to unwrap the view. See [the guide](https://github.com/nalexn/ViewInspector/blob/master/guide.md) for more info.

**Comment by gedaiu** [comment]
Hmmm... I am already extending my view with `Inspectable` and this error is interesting because `subject` is `AnnotationView`

is there a way to debug the hierarchy of the views from `subject`?


```
subject = AnnotationView(feature: feature)

let shape = try subject
                        .inspect()
                        .anyView()
                        .shape(0)

struct AnnotationView: View {
    var body: some View {
        ZStack {
            Circle()
                .fill(Color.white)
                .frame(width: 40, height: 40)

            Circle()
                .strokeBorder(Color.blue, lineWidth: 1)
                .frame(width: 40, height: 40)
        }
        .onReceive(feature.$firstIcons) { value in
           ...
        }
        .task {
           ...
        }
    }
}

```

**Comment by nalexn** [comment]
Here is the chain that gets to the first Shape:

```swift
let shape = try subject.inspect().zStack().shape(0)
```

**Comment by nalexn** [comment]
Feel free to reopen the ticket if the suggestion above did not help
