### ISSUE TITLE
Accessing a custom view with generic type

### ISSUE THREAD

**Issue by YuantongL** [nalexn/ViewInspector#16]
I'm trying to access a custom view like
```
public struct CustomControl<T>: View where T: View {   
    public init() {}
    public var body: some View {
        ... do something with the T
    }
}
```
using
```let _ = try? someView.view(CustomControl<Text>.self)```
I have to provide a type Text, is there a way I can omit the type?

**Comment by nalexn** [comment]
@YuantongL the current framework's API does not allow that. I've checked the implementation and this is possible to add, however, the result of the call won't have `actualView` property for accessing the underlying typed view. The contents of the `body` will be inspectable, but you'd still need the `T` type information for further inspection that works for an arbitrary `T`.

In my opinion it is sufficient to test the `CustomControl` with one or two concrete `T` views just to make sure it constructs the hierarchy correctly
