### ISSUE TITLE
Question - how to take snapshots

### ISSUE THREAD

**Issue by bukira** [nalexn/ViewInspector#160]
This is more a question than an issue,

While running test, is there a way to take snapshots, for example

                    let sut = ContactsDiallerView(isShowingContactsSelection: .constant(true), parentViewModel: diallerViewModel!)
                    
                    let exp = sut.inspection.inspect { view in
                        expect(getView(from: view, ofType: ContactsDiallerViewContent.self)).notTo(beNil())
                    }

                    ViewHosting.host(view: sut.environmentObject(viewModelFactory!).environmentObject(services!))
                    self.wait(for: [exp], timeout: 5.0)

during the "exp" take a snapshot of what changed

**Comment by matis-schotte** [comment]
Very much interested in this, too.

**Comment by nalexn** [comment]
If we're talking about a graphical snapshot, you can try using [this helper](https://github.com/nalexn/EnvironmentOverrides/blob/7e32fb28495b93feece542a11782387edb08a545/Sources/EnvironmentOverrides/GeneralHelpers.swift#L95) from another SwiftUI library of mine.
It is essentially using UIKit API to capture the entire screen's snapshot. If you want to do this from the test, you do need to host the view, and make the snapshot from inside `.inspect { ... }` while the view is on screen.

Let me know if this helps. I might consider adding this feature to the library

**Comment by bukira** [comment]
Well with iOS 16 now doing images from views then there’s not much point anymore :)

**Comment by nalexn** [comment]
@bukira could you elaborate more on that? I didn't get to this yet

**Comment by nalexn** [comment]
Yeah, `ImageRenderer` is providing the requested functionality.
