### ISSUE TITLE
'find' depends on view structure (implementation detail)

### ISSUE THREAD

**Issue by SumoSimo** [nalexn/ViewInspector#161]
Hi there. Please consider the following example:

**View Structure**

```
struct ContentView: View {
  
  var body: some View {
    VStack {
      NestedContentView()
    }
  }
  
}

struct NestedContentView: View {
  
  var body: some View {
    Text("Hello, world!")
      .padding()
  }
  
}
```

**Test**
```
extension ContentView: Inspectable {}

class ContentViewSpecs: QuickSpec {
  
  override func spec() {
    super.spec()
    
    describe("A content view") {
      
      it("should do this") {
        let subject = ContentView()
        
        let helloWorldText = try? subject.inspect().find(text: "Hello, world!")
        
        expect(helloWorldText).toNot(beNil())
      }
      
    }
  }
  
}
```

This test fails because the text containing "Hello, world!" is contained inside of `NestedContentView`. However, this test should still pass in order to uphold good testing philosophy.

When I had originally constructed `ContentView` to contain the `Text`, the test passed, which is expected. I then refactored the `Text` into `NestedContentView`. I should expect the test to still pass, but as I mentioned, it now fails. This is just a trivial example, but it is a common pattern for non-trivial work as well.

Essentially, because the test fails after refactoring, the test becomes moot because tests shouldn't have to know about implementation details.

Is there any way to use `find` in the way I just described?

**Comment by nalexn** [comment]
hey, the problem is that you've introduced a new custom view on the way to the "Hello, world", and did not add `Inspectable` conformance:

```swift
extension NestedContentView: Inspectable { }
```

You would have noticed it if you didn't silence the exceptions thrown by the library with `try?`, I highly recommend you structure your tests so the exceptions are not discarded.
