### ISSUE TITLE
How to access stacks inside a GeometryReader

### ISSUE THREAD

**Issue by bukira** [nalexn/ViewInspector#162]
I am trying to access the stacks inside a GeometryReader

let filterStack = try! view.zStack().vStack(0).geometryReader(1).zStack(0).hStack(1)

But I am getting the following errors

Referencing instance method 'zStack' on 'InspectableView' requires that 'ViewType.GeometryReader' conform to 'MultipleViewContent'

**Comment by nalexn** [comment]
hey, try to remove `0` for the `zStack(0)`, like so:

```swift
geometryReader(1).zStack()
```

**Comment by bukira** [comment]
Genius :-)
