### ISSUE TITLE
Library not loaded: @rpath/libXCTestSwiftSupport.dylib

### ISSUE THREAD

**Issue by ricdev** [nalexn/ViewInspector#174]
Encountering the following. This happens whenever I add the library via SPM:

Original error:
ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'
ld: warning: Could not find or use auto-linked framework 'XCTest'

setting ENABLE_TESTING_SEARCH_PATHS to YES shows:
Xcode_13.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libXCTestSwiftSupport.dylib' (no such file)
Library not loaded: @rpath/libXCTestSwiftSupport.dylib

How to replicate
- Open Xcode 13.3
- new Project
- Import via SPM ver 0.9.1

**Comment by nalexn** [comment]
Hey, please have a look at #146 and let me know if this helps
