### ISSUE TITLE
Inspecting ViewController (UIHostingController)

### ISSUE THREAD

**Issue by MikePendo** [nalexn/ViewInspector#178]
Hi
Is it possible to inspect a view controller at run time. I.e SwiftUI creates UIHostingController whenever, it appears I would like to inspect it contents and get all the buttons (for instance). I have written my own reflector and after   I traverse over all the label/child there are no types like buttons or gestures. Is it possible to achieve it?

**Comment by nalexn** [comment]
As discussed on a call, it doesn't appear to be possible to use ViewInspector or a similar tool to traverse the SwiftUI hierarchy hosted by the running app without access to the actual view types and the ability to extend them with `Inspectable` protocol conformance.

**Comment by nalexn** [comment]
The above comment is stale - `ViewInspector` has advanced since then and no longer requires `Inspectable` protocol conformance, so that possibility has to be re-evaluated

**Comment by MikePendo** [comment]
Hi @nalexn 
Nice to hear from you, we have also advanced in that area and now we manage to detect what elements are clickable  read the accessibility properties for use for click analytics ([Pendo SDK](https://github.com/pendo-io/pendo-mobile-sdk?tab=readme-ov-file)).
The current limitation on SwiftUI is a little stale, I will update it after our next release.

Thanks again for your help !
