### ISSUE TITLE
Toggle<Text> does not have '_isOn' attribute

### ISSUE THREAD

**Issue by bukira** [nalexn/ViewInspector#193]
HI,

Ive installed Xcode 14 and when running tests that worked before I am now getting

__lldb_expr_13/<EXPR>:6: Fatal error: 'try!' expression unexpectedly raised an error: Toggle<Text> does not have '_isOn' attribute

**Comment by nalexn** [comment]
Hey, yes, there are several changes in the inner structure of the Toggle in iOS 14. I'm tracking this as part of #177

**Comment by bukira** [comment]
I thought you would be on the case, awesome, keep up the good work, thanks
