### ISSUE TITLE
Unable to test Accessibility Modifiers

### ISSUE THREAD

**Issue by A30007283-Kamyab** [nalexn/ViewInspector#194]
I have recently updated to Xcode 14 and it seems like I am not able to test accessibility modifiers at all.

This is from one of the unit tests in the ViewInspector package and it is failing for me with following error:
`EmptyView does not have 'accessibilityLabel' modifier`

``` swift 
func testAccessibilitylabel() throws {
    let label = "abc"
    let value = "xyz"
    let sut = try EmptyView()
        .accessibility(label: Text(label))
        .accessibility(value: Text(value))
        .accessibility(addTraits: [.isImage])
        .inspect().emptyView()

    XCTAssertEqual(try sut.accessibilityLabel().string(), label)
    XCTAssertEqual(try sut.accessibilityValue().string(), value)
  }
```

Even changing the `EmptyView()` to `Text("")` throws the same error `EmptyView does not have 'accessibilityLabel' modifier`

As seen below, `AccessibilityAttachmentModifier` does not seem to have proper content:

![Screen Shot 2022-09-14 at 1 43 46 pm](https://user-images.githubusercontent.com/78328912/190054714-2fc49517-f021-4df9-a3dd-9617128b3ada.png)

Not sure if it due to the recent updates to Swift and Xcode, but would be great to understand why this is happening.

**Comment by nalexn** [comment]
Hey, yes, this has been addressed as part of the #177, will be released soon
