### ISSUE TITLE
Detect view overlap

### ISSUE THREAD

**Issue by johan-diabeloop** [nalexn/ViewInspector#195]
Hi,
First of all, congratulations for this smart library.

Is there a mean to be sure that a view is not overlapped by an upper view, and is actually visible and hittable ?
For example, In the view below, the button cannot be tapped in reality due to the rectangle.
```swift
struct ContentView: View {
    internal let inspection = Inspection<Self>()

    var body: some View {
        ZStack {
            Button("Button") {}.buttonStyle(.borderedProminent)
            Rectangle().foregroundColor(.black.opacity(0.3))
        }
        .onReceive(inspection.notice) { self.inspection.visit(self, $0) }
    }
}
```

But the following test succeeds, and the state is actually modified by the button tap.
```swift
extension ContentView: Inspectable {}
extension Inspection: InspectionEmissary { }

class ContentViewTests: XCTestCase {

    func testCount() throws {
        let sut = ContentView()
        let exp = sut.inspection.inspect { view in
            let button = try view.find(button: "Button")
            try button.tap()
        }
        ViewHosting.host(view: sut)
        wait(for: [exp], timeout: 0.1)
    }
}
```

**Comment by nalexn** [comment]
Hey, that's a valid feature request, but I doubt it may be added in near future. ViewInspector doesn't do the layout of the views, even when "hosting" them on screen. It cannot report the factual view size, there are limitations on the `GeometryReader` as well (#117).
In order for your request to be fulfilled, the library would essentially need to repeat the entire private logic of the SwiftUI view graph layout system, which is an enormous scope of work.
