### ISSUE TITLE
Xcode 14 Watch app support

### ISSUE THREAD

**Issue by martinwennerberg** [nalexn/ViewInspector#198]
Xcode 14 combines the WatchKit App and WatchKit App Extension targets into a single Watch App target. [Release note](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes).

Please update guide_watchOS.md and ViewHosting.swift to support the new format.

**Comment by nalexn** [comment]
Ok, I'll look into that. Curious to hear your general feedback on using the library for the watch app though!

**Comment by martinwennerberg** [comment]
It's been very useful, and very easy to get going!

**Comment by lodstar** [comment]
Hello @nalexn

I am currently working on watchOS development.
I am grateful that I can use your library to create unit tests.
The project I'm working on is structured as a Watch Kit App, and I'm having trouble with ViewHosting.
So, I have made some modifications to your library and I'm using it.
(https://github.com/lodstar/ViewInspector/commit/8e8fd566947b6304c8f0b53a2aaffe297b5b6043)
It's not the best code, but I would appreciate it if you could take a look and consider updating the main branch.

Thank you!

**Comment by nalexn** [comment]
From what I understand, @lodstar 's PR #251 resolves this ticket. Are there any changes required for `guide_watchOS.md` ? Could you open a PR?

**Comment by nalexn** [comment]
Released in v0.9.8
