### ISSUE TITLE
Accessing non-optional content from a container containing other optional content

### ISSUE THREAD

**Issue by mpiechocki** [nalexn/ViewInspector#2]
Following test will fail now:

```swift
private struct TestView2: View, Inspectable {
    let flag: Bool
    var body: some View {
        HStack {
            Text("ABC")
            if flag { Text("XYZ") }
        }
    }
}

final class OptionalViewTests: XCTestCase {
    func testNonOptionalViewWhenOtherIsMissing() throws {
        let view = TestView2(flag: false)
        XCTAssertNoThrow(try view.inspect().hStack().text(0))
    }
}
```

It happens because the "XYZ" view is optional AND nil by the time it's being inspected, so the Inspector throws a `InspectionError.viewNotFound` error. I don't think there is a simple way or a workaround to fix it :(

What is needed is that
```swift
extension Optional: OptionalViewContentProvider {
    
    func content() throws -> Any {
        switch self {
        case let .some(view):
            return try Inspector.unwrap(view: view)
        case .none:
            throw InspectionError.viewNotFound(parent: Inspector.typeName(value: self as Any))
        }
    }
}
```
this `content()` method could return nil in the second case, but that in turn will make other tests fail as it will not be working correctly for inspecting optional views that are expected to exist but do not :(

EDIT: Well, the only workaround for now actually is making sure all the optional views are existing (are non-nil) before inspecting them.

**Comment by nalexn** [comment]
@mpiechocki I just checked what's going in this case and found the reason.

When optional view is nil you should still be able to extract non-optional Text("ABC"), but it is bundled with the optional view in ToupleView.

The way Inspector works right now is it tries to unwrap that ToupleView and return an array of all contained views, and attempt to access nil optional view throws an exception, which is correct. What is incorrect, is that the unwrapping should work lazily, and Inspector should not try to access optional view unless we ask it to. I'll work on the fix. Thanks for the heads up!

**Comment by mpiechocki** [comment]
Great! Remember: you're doing an awesome job with this library! :)

**Comment by nalexn** [comment]
I've pushed a new version 0.0.9, should be fixed now

**Comment by mpiechocki** [comment]
Working like a charm now! Thanks! :)

**Comment by rojasjandro89** [comment]
In this very example, how do I check that in fact the second text is not displayed if the flag is false. Let’s say that’s my assertion, how should I proceed?

**Comment by nalexn** [comment]
@rojasjandro89 

Here are two tests for comparison:

```swift
func testNonOptionalViewWhenOtherIsMissing() throws {
        let view = TestView2(flag: true)
        XCTAssertNoThrow(try view.inspect().hStack().text(0))
        XCTAssertNoThrow(try view.inspect().hStack().text(1))
}
```

and the one you requested:

```swift
func testNonOptionalViewWhenOtherIsMissing() throws {
    let view = TestView2(flag: false)
    XCTAssertNoThrow(try view.inspect().hStack().text(0))
    XCTAssertThrowsError(try view.inspect().hStack().text(1))
}
```
