### ISSUE TITLE
Doesn't compile for watchOS

### ISSUE THREAD

**Issue by nrivard** [nalexn/ViewInspector#20]
The library says watchOS is supported but when I try to build, either by opening as a package in Xcode (_not_ the .xcodeproj file) or as a dependency in another project, I get failures due to the use of `XCTest` which isn't supported.

```
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator6.1.sdk/usr/lib/swift/XCTest.swiftmodule/i386.swiftinterface:6:19: XCTest is not available when building for watchOS Simulator. Consider using `#if targetEnvironment(macCatalyst)` to conditionally import this framework when building for Mac Catalyst.
```

```
./SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/InspectableView.swift:2:8: Failed to load module 'XCTest'
```

**Comment by nalexn** [comment]
Yea, I'm aware of this issue. Do you have an Apple Watch to try building for?
I was hoping this is just an issue for watchOS simulator, due to the message Xcode prints out:

> XCTest is not available when building for watchOS Simulator

So I cannot verify if it builds for a real Watch or not

**Comment by nalexn** [comment]
I can make the framework compile by conditionally disabling several helpers from the public API of the framework. Not sure if it's the right way out

**Comment by nrivard** [comment]
There just is no XCTest support for watchOS. The cleanest solution is to wrap all XCTest related code in an `#if`. I tried using:
```swift
#if canImport(XCTest)
  import XCTest
#endif

@available(iOS 13, tvOS 13, macOS 10.15, *)
final class SomeTest: XCTestCase {
}
```
but there are some grumblings in stackoverflow that this statement does not work in swift packages. I can confirm that it didn't work for me. Instead, you will likely have to wrap code via:
```swift
#if !os(watchOS)
import XCTest

final class SomeTest: XCTestCase {
}

#endif

**Comment by nalexn** [comment]
If watchOS does not have `XCTest`, does it mean there is no official way to test a watchOS app?

I think there are two options:
1. Remove the support for watchOS, as ViewInspector is useless for this platform
2. Provide limited API of the ViewInspector for watchOS for a case if someone needs to inspect the app in production
3. Add a [third-party implementation](https://github.com/dfed/XCTest-watchOS) of XCTest and migrate the framework to work with it

@nrivard what are your thought?

**Comment by nrivard** [comment]
I think it makes sense to remove watchOS support. This is a library that is tightly coupled with XCTest and there are no officially supported ways to use XCTest on watchOS.

**Comment by nalexn** [comment]
Well, there are just two exported modules that have `import XCTest`, so in theory, it's not hard to decouple `XCTest`. But I think you're right, it's better to drop the watchOS for now.

**Comment by nalexn** [comment]
Removed for `v0.3.8`
