### ISSUE TITLE
Injecting ```.environment(\.horizontalSizeClass, .regular)``` is not working

### ISSUE THREAD

**Issue by Ricardo1980** [nalexn/ViewInspector#201]
Hello,

I have a view that its layout depends on the current horizontalSizeClass, using:
`@Environment(\.horizontalSizeClass) var horizontalSizeClass`
So:
If regular, then the lazy vertical number of columns is 4.
If compact, then the lazy vertical number of columns is 2.

I am trying to do something like:

```
let sut = MyView().environment(\.horizontalSizeClass, .regular)
let columns = try homeTiles.environment(\.horizontalSizeClass, .regular).inspect().find(ViewType.LazyVGrid.self).columns()
XCTAssertEqual(columns.count, 2)
```

I also tried using `ViewHosting/environmentObject/didAppear`. 
But no luck, `compact` is always used and I cannot test `regular`.

The documentation mentions:
```
For the case of @Environment or @EnvironmentObject, you can perform the injection before hosting the view:
ViewHosting.host(view: sut.environmentObject(...))
```
That's not working.
Or perhaps it is working, but not with properties from the operating system, like `horizontalSizeClass`

I tried creating a `UIViewController` container and overriding `traitCollection`, but it does not work.

Maybe somehow using `setOverrideTraitCollection` from UIKit?

Anyway, how should I do this? Why is this not working?
Thanks a lot.

**Comment by gee-whiz** [comment]
@Ricardo1980  I'm also facing the same issue I tried this  ViewHosting.host(view: view.environment(\.horizontalSizeClass, .compact)), It sort of enters the **regular** but then skips back to compact.

**Comment by nalexn** [comment]
Hey, I confirm that `@Environment` variables are not being updated properly - existing ticket #131. It's not a trivial fix, a solution is under investigation
