### ISSUE TITLE
Feature Request: Make modifierAttribute public

### ISSUE THREAD

**Issue by rsarker** [nalexn/ViewInspector#21]
Is it possible to make modifierAttribute as public so that we can extend it and add support for more modifiers? Unless there is a way to actually add support for different modifiers that are not available currently.
For example, for 
1. Texts, there is no function to return the **Font or Color** of the Text.
2. For Stacks, no function to return **Spacing or Alignment.**

**Comment by nalexn** [comment]
I think `modifierAttribute` is too generic for exposing as a public API. You can submit a PR where you use `modifierAttribute` to extract the specific attribute like **Font**. This way you'd help the community as well.
