### ISSUE TITLE
Running tests on iPhone simulator results in crash

### ISSUE THREAD

**Issue by bachand** [nalexn/ViewInspector#217]
I am developing using Xcode 14.1 on macOS 13.1. My Mac has an M1 processor. I opened the Package.swift and ran the tests (<kbd>Cmd</kbd> + <kbd>u</kbd>) for the iPhone 14 Pro simulator on the HEAD SHA of the master branch (ac7df67c4e0593470eda90a550f8493a81609745). I encounter a crash in `TimelineViewTests.testEnclosedView()`.

<img width="2026" alt="Screenshot 2022-12-18 at 5 18 12 PM" src="https://user-images.githubusercontent.com/1791049/208330244-b26c4493-9514-4ddc-995c-01509150a92b.png">
<img width="2026" alt="Screenshot 2022-12-18 at 5 18 15 PM" src="https://user-images.githubusercontent.com/1791049/208330247-1ff8344c-d396-49ce-8de6-67a7e16e114a.png">

**Comment by nalexn** [comment]
Thanks for the report, this has been fixed for the coming release

**Comment by bachand** [comment]
Great thanks @nalexn . Do you recommend working on this project using the Package.swift or by opening the Xcode project in the repo?

**Comment by nalexn** [comment]
I'm personally more used to using the Xcode project. The only downside of using Package is that it doesn't automatically add new files to the project's structure and doesn't allow arranging the files in the IDE.

**Comment by nalexn** [comment]
Fixed released with v0.9.4
