### ISSUE TITLE
[Import error] No such module 'ViewInspector'

### ISSUE THREAD

**Issue by mfdeveloper** [nalexn/ViewInspector#22]
**Xcode version:** 11.4
**Swift version:** 5.1
**Cocoapods version:** 1.9.1

Hello there!!

I'm trying add this package into my project to `SwiftUI` tests targets, and I've found the error below:

![viewinspector-import-error](https://user-images.githubusercontent.com/431606/78283953-820f6a00-7516-11ea-8d61-80a649c5f8a5.png)

I tried use this package with **Swift package manager** and with **Cocoapods**, and the library is not found with both package managers. I've tried import this package in two targets: Unit and UI Tests, and the problem is the same for both.

I've added another library to my `Xcode 11` project/workspace and works great!

Do you know what I'm doing wrong?

**Comment by nalexn** [comment]
Hey @mfdeveloper !
This is hard to tell what exactly what went wrong, as there are many cases that cause this, but I'd suggest trying different troubleshooting techniques you can find by searching for "No such module CocoaPods" and "No such module Swift Package manager". There are [couple](https://github.com/kareman/SwiftShell/issues/47) of [links](https://stackoverflow.com/questions/57165778/getting-no-such-module-error-when-importing-a-swift-package-manager-dependency) just to start with.

I'd try clearing the DerivedData, relaunching Xcode and then following the integration steps from the readme (and not integrating the library manually)

Also, you can check if a [sample project](https://github.com/nalexn/clean-architecture-swiftui) compiles and the tests run. That project has the ViewInspector integration and it should pull it automatically

**Comment by mfdeveloper** [comment]
Hey @nalexn !

Thank you sooo much for your quickly response! I read this articles that you post in your comment, follow the responses on the threads, but still don't works. 

So, I saw the `ViewInspector` XCode **scheme**, and I try these steps:

1. Change the scheme by side of **Stop** button on XCode

![viewinspector-scheme](https://user-images.githubusercontent.com/431606/78304442-ad09b600-7536-11ea-8312-96fbadfa2e1f.png)

2. Clean project (_Command + SHIFT + K_) and after that, Build (_Command + B_)

3. Change back for your default scheme (commonly the same name of your build target)

4. The `import ViewInspector` works!!

Thank you so much for your help! The responses in articles don't works directly, but everybody mention the **scheme**, and I can pay attention it

**Comment by nalexn** [comment]
Glad you've resolved the issue! Let me know if you need assistance with something else

**Comment by mfdeveloper** [comment]
Thanks a lot for your attention @nalexn !

My last suggestion about this is add this information about build **scheme** (or reference this issue) on [README.md](README.md) file. What do you think?

**Comment by nalexn** [comment]
Usually, you don't need to manually compile CocoaPods targets as they should be set as a prerequisite for the main app target. There is something wrong with your current CocoaPods integration, did you run `pod install` and then open the xcworkspace, as opposed to the original xcodeproj?
Anyway, I think it would be worthwhile adding this in the readme if more people face this issue, for now, I'd just keep the reference in the `Issues`.

**Comment by mfdeveloper** [comment]
Yeah, I've recreate **Cocoapods** integration from zero, and I still need compile from the ViewInspector scheme. The same happens to **Swift Package manager**, I don't know why 😞

But ok, no problem. If someone else face this issue, maybe a "troubles" section in _README_ with common errors/mistakes can help!

**Comment by davidakoontz** [comment]
I've found a similar issue: No such module 'ViewInspector'
Reading this thread I Switched Schemes in XCode to the ViewInspector > iPhone 11 Pro
Then ran the build and the test ran... XCode at some point switched the Scheme back to my Project's Scheme to run the test.
Seems to run - but not a different issue.

**Comment by lucasfeijo** [comment]
I had the same issue described here. Switch to the ViewInspector target in the scheme dropdown, clean and build, then the tests will run.

**Comment by lucasfeijo** [comment]
Figured it out. The dependency must be added by name to the test target too. Follow this pattern: https://stackoverflow.com/a/63223261/1346618
