### ISSUE TITLE
`findAll` api returns an array of duplicated view in hierarchy 

### ISSUE THREAD

**Issue by kiarashvosough1999** [nalexn/ViewInspector#222]
I am trying to inspect some views built using `UIViewrepresentable` inside a `List`. when I try to find them the API below returns 4 duplicated elements of type `UISwitch`(The object's reference hex values are exactly the same) instead of returning 4 unique  `UISwitch`:

```swift
List {
     SwitchViewRepresentable()
     SwitchViewRepresentable()
     SwitchViewRepresentable()
     SwitchViewRepresentable()
}


try view.findAll(SwitchViewRepresentable.self).map { $0.actualView().uiView() }
```

Note that the duplicated element is the first view on the list. other views after the first are not considered at all during the inspection.

@nalexn

**Comment by nalexn** [comment]
Hey, yep, that's a known issue: #166 I'll prioritize the work on fixing this

**Comment by nalexn** [comment]
Please subscribe on that ticket, I'll close this one as duplicate
