### ISSUE TITLE
Cannot find `.alert` modifier on iOS 16

### ISSUE THREAD

**Issue by nodediggity** [nalexn/ViewInspector#225]
I'm perhaps missing something but I am struggling to find an `alert` in my tree, even in the most simple of views, using the iOS 15+ alert modifiers.

Given the structure below, I would expect in test to find the alert - however I have the error:

> test_alert(): failed: caught error: "ExampleView does not have 'alert' modifier" 

As the alert is _on_ the `VStack` I have also tried `let alert = try sut.inspect().vStack().alert()` but this has the same failure:

> test_alert(): failed: caught error: "VStack<ModifiedContent<Button<Text>, AccessibilityAttachmentModifier>> does not have 'alert' modifier"

I am running on iOS 16 w/ ViewInspector 0.9.5.

```swift
import SwiftUI
import ViewInspector
import XCTest

struct ExampleView: View {
    @State private var presentAlert = false

    var body: some View {
        VStack {
            Button {
                presentAlert = true
            } label: {
                Text("Hello, World!")
            }
            .accessibilityIdentifier("ERROR_BUTTON")
        }
        .alert("This is the title", isPresented: $presentAlert, actions: { }, message: {
            Text("This is the message")
        })
    }
}

final class ExampleViewTests: XCTestCase {
    func test_alert() throws {
        let sut = ExampleView()
        let button = try sut.inspect().find(viewWithAccessibilityIdentifier: "ERROR_BUTTON").button()
        try button.tap()

        let alert = try sut.inspect().alert()
    }
}
```

The docs mention if I am using the iOS 15+ API's I should be good to go, but something is a miss here.

Any guidance would be much appreciated!

Thank you!

**Comment by JOyo246** [comment]
have you looked at [this guide](https://github.com/nalexn/ViewInspector/blob/0.9.6/guide_popups.md#alert) on alerts?

**Comment by nodediggity** [comment]
> have you looked at [this guide](https://github.com/nalexn/ViewInspector/blob/0.9.6/guide_popups.md#alert) on alerts? 

Yes, I'm sure I am missing something though or perhaps they are unclear - using iOS 16 I can't seem to make any assertions against the alerts, admittedly it's been sometime since I looked at this so perhaps it needs fresh eyes 🤔

**Comment by JOyo246** [comment]
If you take a look at the guide, you'll see that it doesn't work with the "vanilla" .alert. You make a wrapper for it which gives VI the knowledge of the alert being presented or not.

**Comment by nalexn** [comment]
Hey - apologies for the late response. The problem in your case is that your view uses `@State`. 
The [guide](https://github.com/nalexn/ViewInspector/blob/0.9.6/guide.md#views-using-state-environment-or-environmentobject) instructs that you should use the async approach when inspecting such views - this way the state would be retained correctly after `try button.tap()`. Inside the async inspection call, do `try button.tap()` and then call to find the text inside the alert using the same reverence to the inspected view - do not call `.inspect()` on the original instance, as this will create a copy not referencing the state again
