### ISSUE TITLE
Can't inspect contextMenu(menuItems:)

### ISSUE THREAD

**Issue by rafael-assis** [nalexn/ViewInspector#229]
The following test in the repo inspects a Text element that has a context menu item with other views:

https://github.com/nalexn/ViewInspector/blob/7a45551ab00f0ff9c8a0996374edcba73705438b/Tests/ViewInspectorTests/SwiftUI/TreeViewTests.swift#L9-L14

Calling inspect on the `Text("Test")` element retrieves itself but there's no way to get the list of views in the context menu: `Text("Menu")` in the test case scenario.

I did investigate a bit on that and the reason it doesn't work on iOS 14.5 is because the following code looks for the `root|content` which contains the element that triggers the context menu. The context menu Views are in the `content` property as the structure below shows:

**Code:**
https://github.com/nalexn/ViewInspector/blob/4effbd9143ab797eb60d2f32d4265c844c980946/Sources/ViewInspector/SwiftUI/TreeView.swift#L11-L14

**Internal structure on iOS 14.5:**
```
▿ Content
  ▿ view : Tree<Container<Text>, Optional<ModifiedContent<AnyView, StyleContextWriter<MenuContext>>>>
    ▿ root : Container<Text>
      ▿ content : Text
        ▿ storage : Storage
          ▿ anyTextStorage : <LocalizedTextStorage: 0x7f8f79522820>
        - modifiers : 0 elements
      ▿ contextMenu : Optional<_ContextMenuContainer>
        - some : SwiftUI._ContextMenuContainer()
    ▿ content : Optional<ModifiedContent<AnyView, StyleContextWriter<MenuContext>>>
      ▿ some : ModifiedContent<AnyView, StyleContextWriter<MenuContext>>
        ▿ content : AnyView
          ▿ storage : <AnyViewStorage<ModifiedContent<Text, StyleContextWriter<MenuContext>>>: 0x7f8f79522f50>
        - modifier : SwiftUI.StyleContextWriter<SwiftUI.MenuContext>()
  ▿ medium : Medium
    - viewModifiers : 0 elements
    - transitiveViewModifiers : 0 elements
    - environmentModifiers : 0 elements
    - environmentObjects : 0 elements
```

**Internal structure on iOS 16.2:**

On iOS 16.2 the internal structure is different and the tree is only on the `menuView` property, but it's still no way to inspect them:
```
▿ Content
  ▿ view : ModifiedContent<Text, ContextMenuModifier<ZStack<ModifiedContent<Text, StyleContextWriter<MenuStyleContext>>>>>
    ▿ content : Text
      ▿ storage : Storage
        ▿ anyTextStorage : <LocalizedTextStorage: 0x0000600000d1a440>: "Test"
      - modifiers : 0 elements
    ▿ modifier : ContextMenuModifier<ZStack<ModifiedContent<Text, StyleContextWriter<MenuStyleContext>>>>
      ▿ _id : IdentityLink
        ▿ _value : ViewIdentity
          - seed : 0
      ▿ _activeMenuID : Environment<ViewIdentity>
        ▿ content : Content
          - keyPath : <WritableKeyPath<EnvironmentValues, ViewIdentity>: 0x600003b2d100>
      ▿ _menuOrder : Environment<MenuOrder>
        ▿ content : Content
          - keyPath : <WritableKeyPath<EnvironmentValues, MenuOrder>: 0x600003b2d180>
      ▿ menuView : ZStack<ModifiedContent<Text, StyleContextWriter<MenuStyleContext>>>
        ▿ _tree : Tree<_ZStackLayout, ModifiedContent<Text, StyleContextWriter<MenuStyleContext>>>
          ▿ root : _ZStackLayout
            ▿ alignment : Alignment
              ▿ horizontal : HorizontalAlignment
                ▿ key : AlignmentKey
                  - bits : 2
              ▿ vertical : VerticalAlignment
                ▿ key : AlignmentKey
                  - bits : 5
          ▿ content : ModifiedContent<Text, StyleContextWriter<MenuStyleContext>>
            ▿ content : Text
              ▿ storage : Storage
                ▿ anyTextStorage : <LocalizedTextStorage: 0x0000600000d34cd0>: "Menu"
              - modifiers : 0 elements
            - modifier : SwiftUI.StyleContextWriter<SwiftUI.MenuStyleContext>()
  ▿ medium : Medium
    - viewModifiers : 0 elements
    - transitiveViewModifiers : 0 elements
    - environmentModifiers : 0 elements
    - environmentObjects : 0 elements
```

**Comment by nalexn** [comment]
Published with 0.9.6 release

**Comment by a-shatou** [comment]
I have been trying to inspect the context menu (like the one shown above but without ContextMenu initializer) but still cannot inspect any of the elements inside the context menu. Is there any working example? 🤔 couldn't find one the docs.

**Comment by rafael-assis** [comment]
> I have been trying to inspect the context menu (like the one shown above but without ContextMenu initializer) but still cannot inspect any of the elements inside the context menu. Is there any working example? 🤔 couldn't find one the docs.

@a-shatou are the tests added in #228 useful for you?
