### ISSUE TITLE
[CustomView] View is not found 

### ISSUE THREAD

**Issue by mfdeveloper** [nalexn/ViewInspector#23]
Hello @nalexn !

I'm trying test a custom view that contains a `@ViewBuilder` implementation and a specific `ActivityIndicator` in your body. The code is something like below:

```swift
struct ActivityIndicatorView<Content: View>: View {
    
    @Binding
    var isShowing: Bool
    
    let content: Content

   var body: some View {
        // others parent views
        ...
        // Show a loading icon
        ActivityIndicator()
   }
    
    init(isShowing: Binding<Bool>, @ViewBuilder content: () -> Content) {
        _isShowing = isShowing
        self.content = content()
    }
}
```

So, my `CustomView` class use this `ActivityIndicatorView` in your body. The others view are children of this activity view, like this:

```swift
struct ContentView: View {

      @State
       var showLoadingView: Bool = false

      var body: some View {

         ActivityIndicatorView(isShowing: .constant(showLoadingView)) {
            
            VStack {
                NavigationView {
                 }
             }
         }
     }
}
```

So, how can I test this, to get the `VStack` and `NavigationView` from `ContentView => ActivityIndicatorView` ? I tried the code below in my test class:

```swift
import ViewInspector

// Add Inspectable to the two views
extension ContentView : Inspectable { }
extension ActivityIndicatorView : Inspectable { }

class MyClassTests: XCTestCase {
      func testHeadless() throws {
         let sut = ContentView()

         // Tried this, but was that error with the Generic type in ActivityIndicatorView<>
         let activityView = try sut.inspect().view(ActivityIndicatorView.self).anyView()
         
         //Tried this, but I got: 
        // "caught error: "typeMismatch(factual: 
//"ActivityIndicatorView<VStack<NavigationView<EnvironmentReaderView
//<ModifiedContent<ModifiedContent<ScrollView<TupleView<(SearchBar, ImagesRow)>>,
// _PreferenceWritingModifier<NavigationBarTitleKey>>, 
//_PreferenceWritingModifier<NavigationBarItemsKey>>>>>>", expected: "AnyView")"
// let scrollView = try sut.inspect().anyView().vStack().navigationView(0).scrollView(0)
        
          XCTAssertNotNil(scrollView)
     }
}
```

How can I write in the code snippet above, I've always got errors like this:

**`caught error: "typeMismatch(factual: "ActivityIndicatorView<VStack<NavigationView<EnvironmentReaderView<ModifiedContent<ModifiedContent<ScrollView<TupleView<(SearchBar, ImagesRow)>>, _PreferenceWritingModifier<NavigationBarTitleKey>>, _PreferenceWritingModifier<NavigationBarItemsKey>>>>>>", expected: "AnyView")"`**

Can you help me?

**Comment by nalexn** [comment]
@mfdeveloper 
Neither of your views contains `AnyView`, so then you try to extract it by calling `.anyView()` you get the `typeMismatch` error. You need to repeat the actual view structure when you're unwrapping it.

You have provided only portions of the actual code, so I cannot fully replicate your use case, but here is a close example.

Considering `ActivityIndicatorView` is:

```swift
struct ActivityIndicatorView<Content: View>: View {
    
    @Binding var isShowing: Bool

    let content: Content

    var body: some View {
        content
    }

    init(isShowing: Binding<Bool>, @ViewBuilder content: () -> Content) {
        _isShowing = isShowing
        self.content = content()
    }
}
```

and `ContentView` is:

```swift
struct ContentView: View {

    @State var showLoadingView: Bool = false
    
    var body: some View {
        ActivityIndicatorView(isShowing: .constant(showLoadingView)) {
            VStack {
                ActivityIndicator()
            }
        }
    }
}
```

then in the tests, you can extract the `ActivityIndicator` the following way:

```swift
func testContentView() throws {
    let sut = ContentView()
    let activityView = try sut.inspect().view(ActivityIndicatorView<VStack<ActivityIndicator>>.self)
        .vStack().view(ActivityIndicator.self, 0)
    ...
}
```

Notice that I never used `.anyView()`. Moreover, I had to specify the generic parameter for the `ActivityIndicatorView`, which in this case is `VStack<ActivityIndicator>`. In your case the generic parameter is much more complex, that's why I'd recommend testing the `ActivityIndicatorView` independently, without the need to extract it from the `ContentView`. This way the generic parameters will be inferred automatically:

```swift
func testActivityIndicatorView() throws {
    let isShowing = Binding(wrappedValue: true)
    let sut = ActivityIndicatorView(isShowing: isShowing) {
            VStack {
                ActivityIndicator()
            }
        }
    let activityView = try sut.inspect().vStack().view(ActivityIndicator.self, 0)
}
```
You can also refer to the [inspection guide](https://github.com/nalexn/ViewInspector/blob/master/guide.md) for more about how to test the views with `Binding` and `@State`

**Comment by mfdeveloper** [comment]
Hello @nalexn !

I've read your guide in: [Views using @State, @Environment or @EnvironmentObject ,Approach 2](https://github.com/nalexn/ViewInspector/blob/master/guide.md#approach-2) and changed my approach for SwiftUI tests, and for this case, I did the following:

**1) Create a test method for `ActivityIndicator`**

```swift
func testLoadingIndicator() throws {
        let isShowing = Binding(wrappedValue: true)
        let sut = ActivityIndicator(isShowing: isShowing) {
                Text("test")
            }
        let textView = try sut.inspect().geometryReader().zStack().text(0)
        
        XCTAssertEqual(try textView.string(), "test")
    }
```
> **PS:** Here, the `ActivityIndicatorView` was tested, but just for whether is redered or not. It's ok, but still a weak test for my situtation.

**2) Create another test for `ContentView` that contains `ActivityIndicator` and others CUSTOM VIEWS**

```swift
func testContentView() throws {
        let sut = ContentView()
        let exp = sut.inspection.inspect(after: 5) { view in
            XCTAssert(try view.actualView()myViewModel.data.count > 0)
        }

        ViewHosting.host(view: sut)
        wait(for: [exp], timeout: 6)
    }
```

The last test is good, because the generic parameter is inferred, and access my `ViewModel`  property marked as `@Published`, and my test wait for load the remote data.

Thank you so much for your explanations. Generics was made me crazy in this situation 😅
