### ISSUE TITLE
🙏🏾 Please Add Zstack Alignment to test capabilities.

### ISSUE THREAD

**Issue by nalexn** [nalexn/ViewInspector#234]
### Discussed in https://github.com/nalexn/ViewInspector/discussions/233

<div type='discussions-op-text'>

<sup>Originally posted by **kstrib** March 30, 2023</sup>
🙏🏾 Please Add Zstack Alignment to test capabilities. </div>

**Comment by mrk-han** [comment]
Looks like this was merged, can we close the issue then? Thanks @nalexn  --- or do we need a new release?

**Comment by nalexn** [comment]
Published with 0.9.6 release
