### ISSUE TITLE
Access SwiftUI.Image the CGImage based attribute

### ISSUE THREAD

**Issue by dreampiggy** [nalexn/ViewInspector#24]
Currently we have both `.uiImage()` and `.nsImage()`. However, due to some performance or bugs of SwiftUI, we have to use the CGImage based to provide the `SwiftUI.Image`. I want to write test case to ensure this behavior.

Bugs: https://github.com/SDWebImage/SDWebImageSwiftUI/issues/101

See the API: https://developer.apple.com/documentation/swiftui/image/3364311-init

So, please make [this API](https://github.com/nalexn/ViewInspector/blob/0.3.10/Sources/ViewInspector/SwiftUI/Image.swift#L46) public, or provide the correspond API like `.cgImage()`

**Comment by dreampiggy** [comment]
@nalexn  See PR: #25

**Comment by dreampiggy** [comment]
@nalexn  Seems I forgot to update the documentation :)
And, hope for a release tag fot this, so that my framework who need the CGImage can switch back from my forked repo.

![image](https://user-images.githubusercontent.com/6919743/79318198-3d81c680-7f39-11ea-8a36-3c39783a1c20.png)

**Comment by nalexn** [comment]
Tag added. Thank you for your contribution!
