### ISSUE TITLE
.accessibilityLabel can not be accessed within iOS 17 (attributeNotFound)

### ISSUE THREAD

**Issue by cornelius-behrend** [nalexn/ViewInspector#254]
Hi,

given I have a view with
`.accessibilityLabel(Text("Foo"))`

Up to iOS 16.4, this label can be found using `subject.inspect().find(viewWithAccessibilityLabel: "Foo")`.
The same code executed in iOS 17 results in a `attributeNotFound` in ViewSearch `func find(viewWithAccessibilityLabel accessibilityLabel: String)` > `$0.accessibilityLabel()`.

Screenshot from iOS 16.4 and 17.0 to visualize the difference:

iOS 17
<img width="478" alt="iOS 17 screenshot" src="https://github.com/nalexn/ViewInspector/assets/77003328/6e4c0cbc-e6d7-4a0d-8ecf-6886b60e91e7">

iOS 16.4
<img width="531" alt="iOS 16.4 screenshot" src="https://github.com/nalexn/ViewInspector/assets/77003328/6677907e-47a9-4283-bf64-0e78dd13996a">

Any help is appreciated, thanks in advance :)

**Comment by nalexn** [comment]
Thanks for the report, this has been fixed and is pending release

**Comment by nalexn** [comment]
Released in v0.9.8

**Comment by cornelius-behrend** [comment]
Thanks for the fix! ☺️
