### ISSUE TITLE
How to access AsyncImage completion block with phases like empty, success, failure, etc.

### ISSUE THREAD

**Issue by aaasifrz9** [nalexn/ViewInspector#256]
How to access AsyncImage completion block with phases like empty, success, failure, etc.

I am trying to access phases but not able to reach any phase.

```
VStack {
    AsyncImage(url: URL(string: "https://picsum.photos/200")) { phase in
        switch phase {
        case .empty:
            ProgressView()
        case .success(let image):
            image
                .resizable()
                .scaledToFit()
                .padding(.horizontal, 32)
        case .failure:
            Image("DefaultImage")
        @unknown default:
            // Since the AsyncImagePhase enum isn't frozen,
            // we need to add this currently unused fallback
            // to handle any new cases that might be added
            // in the future:
            EmptyView()
        }
    }
}
```
**Test cases using Quick and Nimble**

```
it("check server image exist") {
    let asyncImage = try subject.inspect().vStack().asyncImage(0)
    expect(asyncImage).toNot(beNil())
    **// Here I am trying to access phases**
}
```
Could you please help me out to access phases? I am not getting any closure access using ViewInspector.
Thanks

**Comment by nalexn** [comment]
Hey @aaasifrz9 , for the code samples, you can always refer to the tests in the project. Here are [tests](https://github.com/nalexn/ViewInspector/blob/0.9.8/Tests/ViewInspectorTests/SwiftUI/AsyncImageTests.swift#L22) you're looking for for `AsyncImage`, the inner views can be accessed with `.contentView(...)` call. LMK if you still have questions!
