### ISSUE TITLE
Issue when inspecting views that interact with navigationBarItems

### ISSUE THREAD

**Issue by nobre84** [nalexn/ViewInspector#29]
Hi! Awesome work here, thank you!
Given this view and its test:
```
struct DetailView: View {
    var body: some View {
        EmptyView()
        .navigationBarItems(trailing: Text("Done")) // commenting this makes the test run fine.
    }
}

func testNavigationBarItems() {
  expect {
    // expected to not throw any error, got <notSupported("Please use \'navigationBarItems()\' for unwrapping the underlying view hierarchy.")>
    try detailView.body.inspect().emptyView()
  }.notTo(throwError())
  expect {
    // expected to not throw any error, got <modifierNotFound(parent: "DetailView", modifier: "navigationBarItems")>
    try detailView.inspect().navigationBarItems().emptyView()
  }.notTo(throwError())
}
```

Is this not supported, or am I missing something?

**Comment by nalexn** [comment]
Hey @nobre84 

The first thing I've noticed is `try detailView.body.inspect()`, which made me think you've forgotten to add `extension DetailView: Inspectable { }` in your test scope and had to inspect `body` instead of the view itself. Make sure you have it, and although it's not forbidden, I'd recommend to never call `body` and inspect the main view instead.

`.navigationBarItems()` is quite tricky to break through during the inspection, so I had to put several internal checks that fail the test with different messages to help the developer get to the right inspection call chain.

So you start with this naive test:

```swift
try detailView.inspect().emptyView()
```
and get the failure message:

> caught error: "notSupported("Please use 'navigationBarItems()' for unwrapping the underlying view hierarchy.")"

You add the `navigationBarItems()`:

```swift
try detailView.inspect().navigationBarItems().emptyView()
```
and get another message:

> caught error: "notSupported("Please substitute 'EmptyView.self' as the parameter for 'navigationBarItems()' inspection call")"

So the final revision of the test would be

```swift
try detailView.inspect().navigationBarItems(EmptyView.self).emptyView()
```

I know this all looks awful, but that's the best solution I could find so far for breaking through the `.navigationBarItems`.

For certain views, like

```swift
var body: some View {
    EmptyView()
        .padding()
        .font(.body)
        .navigationBarItems(trailing: Text("Done"))
}
```

the message at the last step would instruct you to substitute a very long generic view:

> caught error: "notSupported("Please substitute 'ModifiedContent<ModifiedContent<EmptyView, _PaddingLayout>, _EnvironmentKeyWritingModifier<Optional<Font>>>.self' as the parameter for 'navigationBarItems()' inspection call")"

A way to mitigate this problem is to move the `.navigationBarItems` up two lines, before the `.padding`. This would not change the way view is rendered, but it'd allow easier inspection, where you'd pass just `EmptyView.self` instead of that long view type.

**Comment by shabib87** [comment]
Hi @nalexn, Thanks for the wonderful library. I am facing a similar issue related to `navigationBarItems`. I have the following view
```swift
struct ContentView: View {
    
    public var body: some View {
        NavigationView {
            Text("Hello world")
                .navigationBarItems(
                    leading: Button(action: {
                        print("Leading button tapped")
                    }, label: {
                        Text("Left Bar Button")
                    }),
                    trailing: Button(action: {
                        print("Trailing button tapped")
                    }, label: {
                        Text("Right Bar Button")
                    })
                )
                .navigationBarTitle(Text("Home"),
                                    displayMode: .inline)
        }
    }
}
```

The following test is passing:
```swift
extension ContentView: Inspectable {}
let sut = ContentView()
_ = try sut.inspect().navigationView().navigationBarItems(Text.self).text()
```

But I am not sure 
- how to test the left and right button tap, and 
- how test navigation title matches "Home"

Any help would be highly appreciated. Thanks!!!

**Comment by nalexn** [comment]
Hey @shabib87 

Inspection of the navbar items and title is currently [not supported](https://github.com/nalexn/ViewInspector/blob/master/readiness.md#configuring-navigation-and-status-bar-views). Navbar modifiers are doing some real black magic under the hood, messing with the global environment settings, and currently I couldn't find a way to crack this.

**Comment by shabib87** [comment]
Thanks for the confirmation. Hope we'll have this feature in some future version.

**Comment by Alexander-techIOS** [comment]
HI @nalexn , I have a similar issue I made a MockView:

```
struct MockView: View {
    let inspection = Inspection<Self>()
    
    var body: some View {
        ZStack {
            VStack {
                Text(/*@START_MENU_TOKEN@*/"Hello, World!"/*@END_MENU_TOKEN@*/)
                CustomView()
            }
            
            NavigationLink("", destination: Text("DetailView"))
        }
        .navigationBarItems(trailing: refreshBtn)
        .onReceive(inspection.notice) { self.inspection.visit(self, $0) }
    }
    
    private var refreshBtn: some View {
        Button("Refresh", action: { })
    }
    
    struct CustomView: View {
        var body: some View {
            VStack {
                Text("First in stack")
                Text("Second in stack")
            }
        }
    }
}
```

This is the test:

```
func test_mock_view() throws {
   let sut = MockView() 
  
   let exp = sut.inspection.inspect { view in 
       XCAssertNoThrow(try view.content())
       let value = try view.content().vStack(0).text(0).string()
       XCAssertEqual(value, "Hello, World!")
   }

   ViewHosting.host(view: sut)
   wait(for: [exp], timeout: 1.0)
}

extension InspectableView where View == ViewType.View<MockView> {
    func content() throws -> InspectableView<ViewType.ZStack> {
        return try navigationView().navigationBarItems(ZStack<VStack<Text>>.self).zStack()
    }
}
```

I got the extension InspectableView from your tests in the example. 
This is the first test. Ideally I want to test the CustomView.
I keep getting the error `failed - Please use 'navigationBarItems()' for unwrapping the underlying view hierarchy.`

The MockView does not have the NavigationView wrapper, deliberately because the View that I would like to test is DestinationView view of a prior NavigationView.

**Comment by nalexn** [comment]
@Alexander-techIOS did you try swapping these two lines in the view?

```swift
        .navigationBarItems
        .onReceive
```

I'm working on more informative error messages right now, so I'll have a look at this case also.

**Comment by Alexander-techIOS** [comment]
Thanks Nalexn, great work on framework!

I tried your suggestion above but it's still the same.

**Comment by nalexn** [comment]
@Alexander-techIOS 

Let me show how I got to a working test:

1. I started with a simple inspection code like this:

```swift
func testF() throws {
    let sut = TestView()
    let exp = sut.inspection.inspect { view in
        try view.zStack()
    }
    ViewHosting.host(view: sut)
    wait(for: [exp], timeout: 1.0)
}
```
It throws a warning `Please use 'navigationBarItems()' for unwrapping the underlying view hierarchy`

2. I revisit the code with this:

```swift
func testF() throws {
    let sut = TestView()
    let exp = sut.inspection.inspect { view in
        try view.navigationBarItems().zStack()
    }
    ViewHosting.host(view: sut)
    wait(for: [exp], timeout: 1.0)
}
```
And I get a new message: `Please substitute 'ZStack<TupleView<(VStack<TupleView<(Text, CustomView)>>, NavigationLink<Text, Text>)>>.self' as the parameter for 'navigationBarItems()' inspection call`

This is unfortunate that the view type is so long, but ViewInspector currently has to ask for the exact view type so the type cast inside could succeed.

3. I update the test:

```swift
func testF() throws {
    let sut = TestView()
    typealias NavBarWrapped = ZStack<TupleView<(VStack<TupleView<(Text, TestView.CustomView)>>, NavigationLink<Text, Text>)>>
    let exp = sut.inspection.inspect { view in
        try view.navigationBarItems(NavBarWrapped.self).zStack()
    }
    ViewHosting.host(view: sut)
    wait(for: [exp], timeout: 1.0)
}
```
And it works! Now we can finish off the inspection

4. Final:

```swift
func testF() throws {
    let sut = TestView()
    typealias NavBarWrapped = ZStack<TupleView<(VStack<TupleView<(Text, TestView.CustomView)>>, NavigationLink<Text, Text>)>>
    let exp = sut.inspection.inspect { view in
        let value = try view.navigationBarItems(NavBarWrapped.self).zStack().vStack(0).text(0).string()
        XCTAssertEqual(value, "Hello, World!")
    }
    ViewHosting.host(view: sut)
    wait(for: [exp], timeout: 1.0)
}
```

**Comment by Alexander-techIOS** [comment]
Ah I see. Yes I did get that, but wasn't sure if I did something wrong.

Noted I need the exact type. 

Thanks!

**Comment by patrickbdev** [comment]
@AXR-Tech feel free to close the issue if your problem is solved.

**Comment by saltyskip** [comment]
Is there anyway to force the view to be AnyView for navigation bar items in the case of a complex stack as the rootview you might crazy long types in your test code

**Comment by nalexn** [comment]
I've recently used another approach to work around a similar case with [unwrapping `Alert`](https://github.com/nalexn/ViewInspector/blob/master/guide.md#alert-sheet-and-actionsheet). We can introduce a substitute for `navigationBarItems` (`navigationBarItems2` for example) with exact same syntax and all, that would not require the type of the underlying view upon unwrapping. The downside is the same as for `Alert` - the need to use a custom modifier instead of the original one in the production code.

**Comment by saltyskip** [comment]
i think the simpler approach is probably to just create a customView around the Vstack

```
var body: some View {
    VStack { /* Super complicated Vstack that requires a very long type */}
        .padding()
        .font(.body)
        .navigationBarItems(trailing: Text("Done"))
}
```

becomes
```
var body: some View {
    ContentView()
        .padding()
        .font(.body)
        .navigationBarItems(trailing: Text("Done"))
}
```

where ContentView is a Vstack with a super complicated type signature

**Comment by nalexn** [comment]
@saltyskip yeah, as of right now this is the way out. I'm rather thinking about a strategy to escape the type substitution at all.

**Comment by nobre84** [comment]
@nalexn oh, sorry for not getting back in here! The initial suggestions did fix the problems I had.
@patrickbdev since your post came in, some fresh discussion started so I'll hold on a bit more to close this, or @nalexn can be free to close it if you think we're done here. It seems to be a real pain point right now so it makes sense people are still having doubts about it.

**Comment by nalexn** [comment]
I'm currently testing in Xcode 13.0 beta 5, and they seem to completely revamp the navigation modifiers in iOS 15. The good news is that they no longer mess with the global environment and use a simple `ModifiedContent` as a base, which promises full access to the navbar items inspection.

**Comment by nalexn** [comment]
`navigationBarItems` modifier no longer block inspection in iOS 15.

ViewInspector [v0.9.0](https://github.com/nalexn/ViewInspector/releases/tag/0.9.0) has added support for `toolbar` inspection, which is the replacement for `navigationBarItems` (deprecated in iOS 15).

I consider the original issue resolved.
