### ISSUE TITLE
Not found Shape in test layer 

### ISSUE THREAD

**Issue by vsricci** [nalexn/ViewInspector#290]
In ViewInspector 0.9.10, my module didnt run layer tests in iphone 14 16.1 - xcode 14.3 

Error - not found Shape
![Screenshot 2024-02-02 at 18 58 18](https://github.com/nalexn/ViewInspector/assets/10771780/47c0174e-e6ec-4ef2-8fdb-bed828b4a90d)

**Comment by nalexn** [comment]
Hey - you're using a pretty old Xcode 14.3 that is bundled with the SDK that doesn't know this type. Please update to the latest stable Xcode 15.2, that should fix it.

**Comment by vsricci** [comment]
thanks, i my business project i cant up now, but i did downgrade of ViewInspector, and, it's work
