### ISSUE TITLE
How to inspect ForEach?

### ISSUE THREAD

**Issue by davisford** [nalexn/ViewInspector#3]
Hi, I have the following View structure:

```swift
                    VStack(alignment: .leading, spacing: 50) {
                        Text("What Organization is this Station for?")

                        ForEach(orgs) { org in
                            VStack {
                                NavigationLink(destination: BrandsView(),
                                               tag: org.id ?? 0,
                                               selection: self.$selectedOrgId) {
                                    EmptyView()
                                }

                                Text(org.name)
                                    .onTapGesture {
                                        self.selectedOrgId = org.id
                                    }
                            }
                        }
                    }
```

I have this pulled out of the outer view as a `var` in a test case.

```swift
let topSection = try orgsView.inspect().zStack().vStack(1).hStack(0).vStack(0)
let value = try topSection.text(0).string()
expect(value).to(equal("What Organization is this Station for?"))
```

Now I want to inspect the `ForEach`, but having trouble figuring out how...

```swift
let forEach = try topSection.forEach(1)
print(forEach)
```

This prints:

```
InspectableView<ForEach>(view: SwiftUI.ForEach<Swift.Array<PosModels.Organization>, Swift.Optional<Swift.Int64>, SwiftUI.VStack<SwiftUI.TupleView<(SwiftUI.NavigationLink<SwiftUI.EmptyView, Salido.BrandsView>, SwiftUI.ModifiedContent<SwiftUI.ModifiedContent<SwiftUI.ModifiedContent<SwiftUI.Text, SwiftUI.AddGestureModifier<SwiftUI._EndedGesture<SwiftUI.TapGesture>>>, SwiftUI._EnvironmentKeyWritingModifier<Swift.Optional<SwiftUI.Color>>>, SwiftUI._AppearanceActionModifier>)>>>(data: [], content: (Function), idGenerator: SwiftUI.ForEach<Swift.Array<PosModels.Organization>, Swift.Optional<Swift.Int64>, SwiftUI.VStack<SwiftUI.TupleView<(SwiftUI.NavigationLink<SwiftUI.EmptyView, Salido.BrandsView>, SwiftUI.ModifiedContent<SwiftUI.ModifiedContent<SwiftUI.ModifiedContent<SwiftUI.Text, SwiftUI.AddGestureModifier<SwiftUI._EndedGesture<SwiftUI.TapGesture>>>, SwiftUI._EnvironmentKeyWritingModifier<Swift.Optional<SwiftUI.Color>>>, SwiftUI._AppearanceActionModifier>)>>>.IDGenerator.keyPath(Swift.KeyPath<PosModels.Organization, Swift.Optional<Swift.Int64>>), contentID: 0), envObject: ViewInspector.Inspector.EnvironmentObjectNotSet())
```

😮 

If I try to just do:

```swift
let obj2 = try forEach.anyView(0)
print(obj2)
```

It throws an error:

```
Printing description of error.viewIndexOutOfBounds:
▿ 2 elements
  - index : 0
  - count : 0
```

What / how can I get at the inner contents of the `forEach`.  I took a look at your `ForEach` tests, but it wasn't quite clear to me -- you have very simple `struct` and `text`.  These are all complex objects with generics embedded, and I can't seem to index into the zero position with `anyView`?

**Comment by nalexn** [comment]
Hey @davisford ,

The "forEach" inspection works the same way as for Stack view. `try forEach.anyView(0)` would not work in your case, `try forEach.vStack(0)` is the correct call, which would return the vStack for the first element of the ForEach. In the same manner, `try forEach.vStack(1)` returns the second one, and so on.

But the error you're observing (`viewIndexOutOfBounds`) implies that your `orgs` array is empty. If there were at least one element, you would get an error that ForEach does not contain AnyView (because you have VStack instead)

**Comment by davisford** [comment]
Hi @nalexn that makes sense now.  I have injected a mock view model in this view's initializer in the test.  When the view's `.onAppear` is called, it populates the orgs array, but this does not appear to be working in a unit test.

I am either mis-understanding something about the eventing in SwiftUI, or it isn't being triggered from the unit test.

**Comment by nalexn** [comment]
The `.onAppear` gets called only when the view is part of the active view hierarchy. In unit tests, you need to manually inject view into the app's content view. You can check my other project where I do this in the tests: https://github.com/nalexn/clean-architecture-swiftui

Another pitfall here is that after the injection, in the `onAppear` callback you should obtain a fresh copy of the  "sut" view by inspecting the active hierarchy from scratch.

Views are structs, so the view you create in the beginning of the test will eventually be an outdated original version of the updated view in the `onAppear` callback.

**Comment by davisford** [comment]
Thanks @nalexn -- makes sense.  I was able to get it working.  Appreciate the good info.
