### ISSUE TITLE
Custom view(builder) example

### ISSUE THREAD

**Issue by nfrydenholm** [nalexn/ViewInspector#30]
Hi

I'm trying out ViewInspector, which seems like a nice option for writing unittests for the views.

I had a few working tests for a view, until I decided to refactor a bit, and introduce a new View as my the root, which is a ViewBuilder.
Now I can't figure out how to extract it's child.

My "base viewbuilder" is defined like this

```
struct FormBaseView<Content: View>: View {

var body: some View {
        content
            .padding()
           ...a few more modifiers....
            .onAppear {
                .....
            }
    }

}
```

In my test - before wrapping the content in the `FormBaseView` I had the following first line 
```
let bodyContainer = try view.inspect().vStack()
```

Now, it's no longer a vStack at the root level, so this one gives a runtime error, which makes sense
`caught error: "typeMismatch(factual: "FormBaseView<TupleView<(ModifiedContent<IDView<AnyView, ViewState>, _TraitWritingModifier<TransitionTraitKey>>, Spacer)>>", expected: "VStack")"`

The problem is, that I haven't figured out the right solution for what to put instead of vStack to make it work. I have tried `view(FormBaseView.Self)` but is uncertain what needs to be done for that to actually compile.

Can you point me in a direction for what is needed to be able to use my `FormBaseView`?

**Comment by nalexn** [comment]
Hey @nfrydenholm 

It turned out that ViewInspector was unable to extract the @ViewBuilder's content. I've added support for this in v0.3.13

```swift
let view = FormBaseView {
    Spacer()
    Text("Abc")
}

let sut = try view.inspect().viewBuilder().text(1)
```


```swift
let view = AnyView(FormBaseView { Text("Abc") })

let sut = try view.inspect().anyView().view(FormBaseView<Text>.self).viewBuilder().text(0)

// When content is 2 or more views:
.view(FormBaseView<TupleView<(Spacer, Text)>>.self)
```

**Comment by nfrydenholm** [comment]
Thanks @nalexn - that was a quick reaction to my question - much appreciated 🙇‍♂️ 👍 

I got it working based on the examples you provided. 👏 

I did bump into an issue, where I had to make a minor change to my code.

Based on the below sample, maybe you can tell if it's expected behaviour 😄 

```swift
        FormBaseView(viewModel: viewModel) {
            view(for: viewModel.viewState)
                .id(viewModel.viewState)
                .transition(.opacity)
            Spacer()
        }

private func view(for viewState: ViewState) -> AnyView { 
.... //switch on viewState and return correct view
}
``` 

If I run a ViewInspector test on this, I get a very literal Tuple back saying the type was expected like this
`FormBaseView<TupleView<(ModifiedContent<IDView<AnyView, ViewState>, _TraitWritingModifier<TransitionTraitKey>>, Spacer)>>`

If I wrap the function call to my private view-function in an `AnyView` then it works
```swift
        FormBaseView(viewModel: viewModel) {
            AnyView(view(for: viewModel.viewState)
                .id(viewModel.viewState)
                .transition(.opacity))
            Spacer()
        }

```
But since that function is already returning an AnyView, it feels like I'm wrapping my code one extra time to satisfy the tests. 
Would it be possible to somehow look at the outcome from a function like that, or is the solution to make sure it's wrapped in an AnyView.

**Comment by nalexn** [comment]
Hey @nfrydenholm 

I double-checked the view extraction code and found out that the requirement for the generic parameter to match the actual inner view type was unnecessary, so this requirement is removed in v0.3.14

The base view type still has to match, but if it has a generic parameter, you can substitute any view type, such as `AnyView` or `EmptyView`:

```swift
    .view(FormBaseView<EmptyView>.self).viewBuilder()
```
