### ISSUE TITLE
Only able to find the first AccessibilityIdentifier applied to a View, unless applied using a ViewModifier.

### ISSUE THREAD

**Issue by JOyo246** [nalexn/ViewInspector#301]
```
struct MyCustomIdentifier: ViewModifier {
    func body(content: Content) -> some View {
        content
            .accessibilityIdentifier("Identifier-InModifier")
    }
}
```

```
extension MyViewTestCase {
    
    func testAccessibilityIdentifiers() throws {
        let v = Text("")
            .accessibilityIdentifier("Identifier-BeforeModifier")
            .modifier(MyCustomIdentifier())
            .accessibilityIdentifier("Identifier-AfterModifier")


        print("---- BEGIN ID Dump ----")
        try v.inspect().printOutAllAccessibilityIdentifiers()
        print("---- END ID Dump ----")
    }
}

```
```
extension InspectableView {
    
    func printOutAllAccessibilityIdentifiers() {
        try? find {
            print(try $0.accessibilityIdentifier())
            return false
        }
    }
    
}
```

Output here is:
```
---- BEGIN ID Dump ----
Identifier-BeforeModifier
Identifier-InModifier
---- END ID Dump ----
```

My Expected Output would be:
```
---- BEGIN ID Dump ----
Identifier-BeforeModifier
Identifier-InModifier
Identifier-AfterModifier
---- END ID Dump ----
```

**Comment by nalexn** [comment]
For some modifiers, which could be applied multiple times in the code, like `background`, inspection function also takes an `index`, so for introspecting the second one you'd write `try sut.inspect().background(1)`.

The API for `accessibilityIdentifier` does not take an index, meaning it only looks up for the first instance. I could amend it to consume the index, but I don't see a point - you're meant to apply only a single `accessibilityIdentifier` per view.

[From the docs](https://developer.apple.com/documentation/uikit/uiaccessibilityidentification/1623132-accessibilityidentifier):

> An identifier can be used to uniquely identify an element in the scripts you write using the UI Automation interfaces. Using an identifier allows you to avoid inappropriately setting or accessing an element’s accessibility label.

Technically this is a limitation of the library API here, but there is no practical use to "fixing" it. Let me know if I'm missing anything.

**Comment by csm-cinemo** [comment]
I would disagree on the assessment that "you're meant to apply only a single `accessibilityIdentifier` per view".

The docs explicitly speak of an _element_ so you could have e.g. a single _view_ with multiple buttons as _elements_, each button having a distinct accessibility identifier. This way you can reliably identify UI elements without having an implicit contract on their relative position within the view or their labels (if they have a label at all - they also might be icon buttons).

In my experience accessibility identifiers beat query paths and title matching all the time, regardless of the testing approach you are using (UIKit-based unit tests, ViewInspector-based unit tests, XCUITests, Appium tests).

But after a second look I think the whole discussion is around multiple accessibility identifiers _on a single element_. In that aspect I agree that this is nothing to be fixed.
