### ISSUE TITLE
Testing accessibilityActions()

### ISSUE THREAD

**Issue by JOyo246** [nalexn/ViewInspector#305]
I know only accessibilityAction() is testable. But any timeline on when accessibilityActions() might be testable? If not, any tips on getting started with trying to add support myself? (would open a PR of course)

seems like it would be simple enough to keep the current `.accessibilityAction()` method, but modify it to also be able to find actions added via `View.accessibilityActions()`

**Comment by nalexn** [comment]
Thanks for the report, this is added for the next release

**Comment by nalexn** [comment]
Released with v0.10.0
