### ISSUE TITLE
[Suggestion]How about screenshot/snapshot testing?

### ISSUE THREAD

**Issue by frankois944** [nalexn/ViewInspector#306]
is It (technically) possible to make a screenshot of an inspected view to make snapshot testing? Or at least, a screenshot, it should be a good start.

It's currently possible with some tool like https://www.browserstack.com/guide/snapshot-testing-ios

On Android, it's now easily possible to screenshot/snapshot testing an app and make some testing faster.

Like https://github.com/cashapp/paparazzi or even google propose an official tool https://developer.android.com/studio/preview/compose-screenshot-testing.

**Comment by frankois944** [comment]
Ah found something that could work
Using this for taking/checking a screenshot : https://github.com/pointfreeco/swift-snapshot-testing

We could use the Framework like this :

```swift
 let sut = ContentView()

 try await ViewHosting.host(sut) { hostedView in
    hostedView.inspect { @MainActor view in
        let actual = try view.actualView()
        assertSnapshot(of: actual, as: .image(layout: .device(config: .iPhone12)))
    }
}
```

**Comment by jverkoey** [comment]
Note for anyone finding this thread, it looks like the approach mentioned here is no longer supported as discussed in https://github.com/nalexn/ViewInspector/discussions/354

**Comment by frankois944** [comment]
This one is working

```swift
let sut = MySwiftUIView()
try await ViewHosting.host(sut) { hostedView in
    try await hostedView.inspection.inspect { view in
        assertSnapshot(of: try view.actualView().body, as: .image(layout: .device(config: .iPhoneSe)))
    }
}
```

**Comment by jverkoey** [comment]
I get a compiler error when I try to do that unfortunately:

<img width="985" alt="Image" src="https://github.com/user-attachments/assets/489082c8-22b9-411d-b0ea-16fd4c528628" />

**Comment by frankois944** [comment]
@jverkoey Oh my bad, I didn't use Swift6, let me check

**Comment by frankois944** [comment]
@jverkoey well I don't know about your _ContentView_, but on full Swift6 with the following example is working fine. 
Check your concurrency.

```swift
@MainActor
@Test func testContentView() async throws {
    let sut = WeatherContent()
    //deprecated one
    try await ViewHosting.host(sut) { hostedView in 
        try await hostedView.inspection.inspect { view in
            assertSnapshot(of: try view.actualView().body, as: .image(layout: .device(config: .iPhoneSe)))
        }
    }
    // the correct one
    try await ViewHosting.host(sut) {
        try await sut.inspection.inspect { view in
            assertSnapshot(of: try view.actualView().body, as: .image(layout: .device(config: .iPhoneSe)))
        }
    }
}
```

**Comment by jverkoey** [comment]
<img width="887" alt="Image" src="https://github.com/user-attachments/assets/13f78dbd-6f06-405c-8bc2-7cd40296363e" />

When I try that same thing I get this error :(

**Comment by jverkoey** [comment]
I can't quite wrap my head around the different between `inspection` and `inspect()`; what do each of them do, and where does inspection come from 🤔
