### ISSUE TITLE
Testing SwiftUI views that are a part of a UITableViewCell

### ISSUE THREAD

**Issue by chrisbrandow** [nalexn/ViewInspector#309]
Not sure if this is possible at all, but when a SwiftUI view is set to the property `.contentConfiguration` on a UITableview cell, there does not seem to be an obvious way to introspect that. It can create a `UIView` object but that has very little useful information.

**Comment by nalexn** [comment]
ViewInspector is built primarily for SwiftUI, there are no plans to extend support for UIKit bridges. I suggest you test your SwiftUI view set as `contentConfiguration` in isolation from UIKit views
