### ISSUE TITLE
Xcode 16 - Action GitHub Failed

### ISSUE THREAD

**Issue by salvatoreboemia** [nalexn/ViewInspector#314]
Hi 

I got this error after launching the unit test in the GitHub Action

`
SwiftCompile normal arm64 /Users/runner/work/myRepo-ios/myRepo-ios/DerivedData/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/ViewSearchIndex.swift (in target 'ViewInspector' from project 'ViewInspector')
`

SPM version -> `0.9.11`

Do you have any fixes on this?

Thanks

**Comment by salvatoreboemia** [comment]
Any news on that? thanks

**Comment by nalexn** [comment]
Please try to use the [branch 0.10.0](https://github.com/nalexn/ViewInspector/tree/0.10.0) instead of pinning to a version in SPM

**Comment by salvatoreboemia** [comment]
> Please try to use the [branch 0.10.0](https://github.com/nalexn/ViewInspector/tree/0.10.0) instead of pinning to a version in SPM

the previous error is solved I think but I have a new error at this line inside the SDK

`throw InspectionError.inspection(path: pathToRoot, factual: factual, expected: expected)`

`
test_MyClass): failed: caught error: "vStack) found MyApp.MyClass instead of VStack"
test_MyClass(): failed: caught error: "text(0) found MyApp.MyClass instead of Text"
`


I don't understand why it shows me an error inside the SDK and not inside the test

however my test had never failed before, there is something wrong with the new version of Xcode 16 or with ViewInspector 0.10.0

Any suggestions here? Thanks a lot

XCode 16 beta 2 
ViewInspector branch 0.10.0

**Comment by nalexn** [comment]
Oh yes, Xcode 16 is messing up with he hierarchy of the views, even the tests we have in ViewInspector run well in Xcode 15 and dozens fail in Xcode 16, most due to different underlying view hierarchy that's been used for the same SwiftUI views. I suggest you use `find` for that custom view you're looking for, then it'd not complain about the VStack suddenly appearing on your way

**Comment by salvatoreboemia** [comment]
> Oh yes, Xcode 16 is messing up with he hierarchy of the views, even the tests we have in ViewInspector run well in Xcode 15 and dozens fail in Xcode 16, most due to different underlying view hierarchy that's been used for the same SwiftUI views. I suggest you use `find` for that custom view you're looking for, then it'd not complain about the VStack suddenly appearing on your way

Thanks, Apple for stressing all of us 😄

Anyway, thanks for your suggestion I replaced it with `find`

<img width="208" alt="Screenshot 2024-07-09 at 10 50 23" src="https://github.com/nalexn/ViewInspector/assets/20614870/333b7f81-3c46-4f4f-bed1-b9ef1ae75697">

Last two questions:

- Do you think the 'find' function could cause issues compared to the previous 'inspect'?
- When will you release the updated version as a new release?

Thank you very much for your support

**Comment by nalexn** [comment]
`find` is the preferred way of locating the view, as it's making your tests less fragile to view structure re-arrangements, be that you or apple.
The updated version is likely to be released shortly after Xcode 16 stable release
