### ISSUE TITLE
Cannot inspect text that uses format override

### ISSUE THREAD

**Issue by waterskier2007** [nalexn/ViewInspector#316]
When using the initializer for a `Text` element that takes a format parameter, view inspector fails to find the text.

```swift
Text(5000, format: .currency(code: "USD"))
```

When I dig down through the inspector, I receive the following error when trying to get the string value from the text element (through `InspectableView<Text>.string()`) I get the following error

```
Unknown text storage: FormatStyleStorage
  - notSupported : "Unknown text storage: FormatStyleStorage"
```

Xcode 15.2
View Inspector 0.9.11
iOS 17.2

**Comment by nalexn** [comment]
Released with v0.10.0
