### ISSUE TITLE
How to work with @EnvironmentObject?

### ISSUE THREAD

**Issue by joemasilotti** [nalexn/ViewInspector#32]
First off, amazing work on this library! I'm looking forward to diving in and testing a few of my apps.

I'm trying to work with a view that uses `@EnvironmentObject` but can't seem to get it to work, even after reading through `guide.md`.

I receive the following error on the `Text(strings.all.first ?? "(none)")` line:
```
Thread 1: Fatal error: No ObservableObject of type Strings found. A View.environmentObject(_:) for Strings may be missing as an ancestor of this view.
```

Here's the smallest amount of code I can write to reproduce the error.

```swift
import XCTest
import ViewInspector

extension StringsView: Inspectable { }

class ViewTests: XCTestCase {
    func testEnvironmentObject() throws {
        let subject = StringsView()

        let strings = Strings(["first", "second"])
        ViewHosting.host(view: subject.environmentObject(strings))

        let text = try subject.inspect().text().string()
        XCTAssertEqual(text, "first")
    }
}
```

```swift
import SwiftUI

class Strings: ObservableObject {
    var all: [String] = []

    init(_ strings: [String]) {
        all = strings
    }
}

struct StringsView: View {
    @EnvironmentObject var strings: Strings

    var body: some View {
        Text(strings.all.first ?? "(none)")
    }
}
```

I'm assuming I'm doing something wrong with either the order of operations or "losing" the reference to the hosting view but I can't tell for sure. Any help would be greatly appreciated!

**Comment by nalexn** [comment]
Hey @joemasilotti 

Your test would work if you had @ObservedObject instead of @EnvironmentObject. They are using different injection mechanics, and SwiftUI does not plug in the environment until the view is about to render on screen. Long story short, your view has to be natively injected in the drawing routine, a synchronous test that you have would not work. You can pick one of the [two approaches](https://github.com/nalexn/ViewInspector/blob/master/guide.md#views-using-state-environment-or-environmentobject) I described in the guide for testing such views. Let me know how it goes!

**Comment by joemasilotti** [comment]
Ah, thanks. I totally skipped that part and dove right into the `@EnvironmentObject` section!

Unfortunately, I'm getting the same error. Here's my updated code which (I think) follows the instructions outlined in the guide.

```swift
import XCTest
import ViewInspector
@testable import HostApp

extension StringsView: Inspectable { }
extension Inspection: InspectionEmissary where V: Inspectable { }

class ViewTests: XCTestCase {
    func testEnvironmentObject() throws {
        let subject = StringsView()

        let test = subject.inspection.inspect { view in
            let text = try subject.inspect().text().string()
            XCTAssertEqual(text, "first")
        }

        let strings = Strings(["first", "second"])
        ViewHosting.host(view: subject.environmentObject(strings))
        wait(for: [test], timeout: 0.1)
    }
}
```

```swift
import SwiftUI
import Combine

class Strings: ObservableObject {
    var all: [String] = []

    init(_ strings: [String]) {
        all = strings
    }
}

struct StringsView: View {
    @EnvironmentObject var strings: Strings
    internal let inspection = Inspection<Self>()

    var body: some View {
        Text(strings.all.first ?? "(none)")
            .onReceive(inspection.notice) { self.inspection.visit(self, $0) }
    }
}

internal final class Inspection<V> where V: View {
    let notice = PassthroughSubject<UInt, Never>()
    var callbacks = [UInt: (V) -> Void]()

    func visit(_ view: V, _ line: UInt) {
        if let callback = callbacks.removeValue(forKey: line) {
            callback(view)
        }
    }
}
```

I'm assuming I'm missing something silly. Any idea what it could be? Thanks in advance for the help.

**Comment by nalexn** [comment]
Ok, I can see where the problem is. Just replace

```swift
let test = subject.inspection.inspect { view in
    let text = try subject.inspect().text().string()
```

with

```swift
let test = subject.inspection.inspect { view in
    let text = try view.text().string()
```

**Comment by joemasilotti** [comment]
Ah, of course! Thank you so much for the help @nalexn :)
