### ISSUE TITLE
Can't inspect List with NavigationLink

### ISSUE THREAD

**Issue by gabrieledintino** [nalexn/ViewInspector#322]
Hello!

I'm trying to inspect this code here:

`struct DriversListView: View {
    @State var viewModel = DriversListViewModel()
    internal let inspection = Inspection<Self>()
    
    var body: some View {
        NavigationView {
            VStack {
                if viewModel.isLoading {
                    ProgressView()
                        .accessibilityIdentifier("progress_view")
                } else if let errorMessage = viewModel.errorMessage {
                    ErrorView(message: errorMessage)
                        .accessibilityIdentifier("error_view")
                } else {
                    driversList
                }
            }
            .navigationTitle("F1 Drivers")
        }
        .searchable(text: $viewModel.searchText, prompt: "Search drivers")
        .onReceive(inspection.notice) { self.inspection.visit(self, $0) }
    }
    
    private var driversList: some View {
        List(viewModel.filteredDrivers, id: \.driverID) { driver in
            NavigationLink(destination: DriverDetailView(driver: driver)) {
                DriverRow(driver: driver)
                    .accessibilityIdentifier("DriverCell_\(driver.driverID)")
            }
        }
        .accessibilityIdentifier("list_view")
    }
}
`

I want to test that the first cell in the list show a cell with the proper DriverRow of the first driver fetched in the ViewModel. If I do this:
`    
func testIssue() throws {
        let view = DriversListView()
        let sut = try view.inspect().find(DriversListView.self)
        let listView = try sut.find(viewWithAccessibilityIdentifier: "list_view")
        XCTAssertEqual(try listView.list(0).navigationLink(0).text().string(), "whatever")
`

It fails because of this:
`XCTAssertEqual failed: threw error "view(DriversListView.self).navigationView().vStack().list(0).list(0).navigationLink(0) found ForEach<Swift.Array<MVVMPrototype.Driver>, Swift.String, SwiftUI.NavigationLink<SwiftUI.ModifiedContent<MVVMPrototype.DriverRow, SwiftUI.AccessibilityAttachmentModifier>, MVVMPrototype.DriverDetailView>> instead of NavigationLink"`

This suggested me to try this example chain to get to the first NavigationLink:
`XCTAssertEqual(try listView.list(0).forEach(0).navigationLink(0).text().string(), "whatever")`
but it gives the error
`testIssue(): XCTAssertEqual failed: threw error "Enclosed view index '0' is out of bounds: '0 ..< 0'"`

As it probably does not find the navigation link.

Am I doing something wrong? How can I get to the DriverRow inside the List/NavigationLink? I've tried all the possible solutions that came to my mind but could not get to it.

Thank you in advance for your help and for all the work you have done on this library @nalexn!

**Comment by nalexn** [comment]
Hey,

Instead of finding `DriversListView`, which is the root view already

```swift
let view = DriversListView()
let sut = try view.inspect().find(DriversListView.self)...
```

try searching for that text right away:

```swift
let view = DriversListView()
let sut = try view.inspect().find(text: "whatever")
```

and then shift focus to a parent view (see [guide](https://github.com/nalexn/ViewInspector/blob/0.10.0/guide.md#parent)). 
 You can also use `.find(MVVMPrototype.DriverRow.self, containing: "whatever")`.

**Comment by gabrieledintino** [comment]
Thank you for your suggestion, I managed to make it work and find DriverRow.self thanks to your help!
You are very kind!
