### ISSUE TITLE
Call to main actor-isolated instance method 'content()' in a synchronous nonisolated context

### ISSUE THREAD

**Issue by perlguy99** [nalexn/ViewInspector#323]
On a clean project, simply adding ViewInspector branch 0.10.0 right now will cause this failure.

![Image 8-9-24 at 11 27](https://github.com/user-attachments/assets/487b316f-2634-41ff-8888-f2dcdde0777f)

**Comment by nalexn** [comment]
Hey @perlguy99 , what is the Xcode version you're using? I'm currently unable to get this error to show up

**Comment by perlguy99** [comment]
Hmm, I just tried with Xcode 15.4 and 16.1beta and it worked. It was probably a 16.0 beta that was doing it. Sorry!

**Comment by sebskuse** [comment]
Looks like this may have been fixed by this: https://github.com/nalexn/ViewInspector/commit/f4c240a8e1c06e246b5f7d32ef9733081cdb1050

**Comment by nalexn** [comment]
Released with v0.10.0
