### ISSUE TITLE
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by Lawlis** [nalexn/ViewInspector#324]
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/fce52921-1ca8-49e4-8bc1-f2d6a2647290">

Using XCode 16.1 beta 1 I get this error

**Comment by nalexn** [comment]
Hey, this is a known issue #307, please pin to the branch 0.10.0 until this version is released
