### ISSUE TITLE
Observable Macro Environment Crash

### ISSUE THREAD

**Issue by hilmyveradin** [nalexn/ViewInspector#329]
I'm encountering an issue when trying to test a SwiftUI view that uses `@Observable` objects in its environment. The view works fine in the app, but crashes during testing with ViewInspector.

Here's a simplified version of my setup:

```
@Observable
class MyEnvironmentObject {
    // properties and methods
}

struct MyView: View {
    @Environment(MyEnvironmentObject.self) private var myEnv

    var body: some View {
        // View content using myEnv
    }
}

class MyViewTests: XCTestCase {
    func testViewStructure() throws {
        let view = MyView()
            .environment(MyEnvironmentObject())
        
        ViewHosting.host(view: view)
        
        let inspectableView = try view.inspect()
        
        // Assertions...
    }
}
```

When I run the test, I get the following error:

```
2024-09-02 11:26:40.404652+0700 xctest[42219:24719477] [SwiftUI] Accessing State's value outside of being installed on a View. This will result in a constant Binding of the initial value and will not update.

2024-09-02 11:26:40.404896+0700 xctest[42219:24719477] [SwiftUI] Accessing Environment<MyEnvironmentObject>'s value outside of being installed on a View. This will always read the default value and will not update.

SwiftUI/Environment+Objects.swift:32: Fatal error: No Observable object of type MyEnvironmentObject found. A View.environmentObject(_:) for MyEnvironmentObject may be missing as an ancestor of this view.

2024-09-02 11:26:40.405242+0700 xctest[42219:24719477] SwiftUI/Environment+Objects.swift:32: Fatal error: No Observable object of type MyEnvironmentObject found. A View.environmentObject(_:) for MyEnvironmentObject may be missing as an ancestor of this view.
```

This is confusing because:

1. I'm using `@Environment`, not `@EnvironmentObject`.
2. The view works correctly in the app.
3. I'm providing the environment in the test.
4. The error suggests that an `@EnvironmentObject` is missing, even though I'm not using `@EnvironmentObject`.

Is this a known issue with testing`@Observable` types using ViewInspector? Are there any workarounds or best practices for testing views that use `@Observable` environment objects? How can we ensure that the environment and state are properly set up before inspection begins?

Any insights or suggestions would be greatly appreciated. Thank you! 🙂

**Comment by nalexn** [comment]
Hey, the library doesn't fully support `@Environment` property wrapper (#131), if you replaced It with `@EnvironmentObject` it would work. Obviously also use `.environmentObject(MyEnvironmentObject())`

**Comment by hilmyveradin** [comment]
> Hey, the library doesn't fully support `@Environment` property wrapper (#131), if you replaced It with `@EnvironmentObject` it would work. Obviously also use `.environmentObject(MyEnvironmentObject())`

Ah understood. Thank you for clarifying this! I think I can't use the `environmentObject` since it will change the whole `@Observable` logic. In the mean time. I think I'll try to test other files that's not directly related to `Environment` 🙂

**Comment by nalexn** [comment]
As a follow-up, I should also note that hosting the view should be the last step, after you setup the inspection. See [this test](https://github.com/nalexn/ViewInspector/blob/0.10.0/Tests/ViewInspectorTests/SwiftUI/CustomViewTests.swift#L36) as an example

**Comment by hilmyveradin** [comment]
> As a follow-up, I should also note that hosting the view should be the last step, after you setup the inspection. See [this test](https://github.com/nalexn/ViewInspector/blob/0.10.0/Tests/ViewInspectorTests/SwiftUI/CustomViewTests.swift#L36) as an example

Ah got it. I'll keep in mind about this. Thank you!
