### ISSUE TITLE
Some way to inspect tuple view children

### ISSUE THREAD

**Issue by asam139** [nalexn/ViewInspector#33]
For example, I have the type InspectableView<ViewType.View<TupleView<(AnyView, AnyView?)>>>, I didn't find a way to get each view to check some properties if it is defined as the tap gesture.

**Comment by nalexn** [comment]
I would be helpful if you posted the actual view structure. From the view type you mentioned I can only assume you have a custom view defined as the view builder. This case has been discussed [here](https://github.com/nalexn/ViewInspector/issues/30), so the `.viewBuilder()` call allows you to unwrap the TupleView inside a custom view. I'm not sure how the tap gesture is related to this, so if you can provide the essential part of the view hierarchy I can help further.

**Comment by nalexn** [comment]
@asam139 please reopen the ticket if you have any questions.

**Comment by bukira** [comment]
I have the same issue
my structure is as follows

struct MyView: View {
    @ObservedObject var data: Data = Data()
    internal let inspection = Inspection<Self>() //for testing UI
    
    var body: some View {
        VStack() {
            Spacer()
            if data.isThis {
                AnyView(SampleView(text: "test1", colour: .gray))
                Spacer().frame(height: 10)
            }
            if data.isThis2 {
                AnyView(SampleView(text: "test2", colour: .green))
                Spacer().frame(height: 10)
            }
            if !data.isOnline {
                AnyView(SampleView(text: "test3", colour: .red))
            }
            Spacer().frame(height: 55)
        }.onReceive(inspection.notice) { self.inspection.visit(self, $0) } //for testing UI
    }
}

so :let text = try view.vStack().anyView(3).view(SampleView.self).text().string()
works and text = "test 3"

however I can't access the other 2 SampleViews as they are Tuples

 InspectableView<VStack>
  ▿ content : Content
    ▿ view : VStack<TupleView<(Spacer, Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>, Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>, Optional<AnyView>, ModifiedContent<Spacer, _FrameLayout>)>>
      ▿ _tree : Tree<_VStackLayout, TupleView<(Spacer, Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>, Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>, Optional<AnyView>, ModifiedContent<Spacer, _FrameLayout>)>>
        ▿ root : _VStackLayout
          ▿ alignment : HorizontalAlignment
            ▿ key : AlignmentKey
              - bits : 140735363993224
          - spacing : nil
        ▿ content : TupleView<(Spacer, Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>, Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>, Optional<AnyView>, ModifiedContent<Spacer, _FrameLayout>)>
          ▿ value : 5 elements
            ▿ .0 : Spacer
              - minLength : nil
            ▿ .1 : Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>
              ▿ some : TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>
                ▿ value : 2 elements
                  ▿ .0 : AnyView
                    ▿ storage : <AnyViewStorage<SampleView>: 0x600003e29bc0>
                  ▿ .1 : ModifiedContent<Spacer, _FrameLayout>
                    ▿ content : Spacer
                      - minLength : nil
                    ▿ modifier : _FrameLayout
                      - width : nil
                      ▿ height : Optional<CGFloat>
                        - some : 10.0
                      ▿ alignment : Alignment
                        ▿ horizontal : HorizontalAlignment
                          ▿ key : AlignmentKey
                            - bits : 140735363993224
                        ▿ vertical : VerticalAlignment
                          ▿ key : AlignmentKey
                            - bits : 140735363993201
            ▿ .2 : Optional<TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>>
              ▿ some : TupleView<(AnyView, ModifiedContent<Spacer, _FrameLayout>)>
                ▿ value : 2 elements
                  ▿ .0 : AnyView
                    ▿ storage : <AnyViewStorage<SampleView>: 0x600003e296c0>
                  ▿ .1 : ModifiedContent<Spacer, _FrameLayout>
                    ▿ content : Spacer
                      - minLength : nil
                    ▿ modifier : _FrameLayout
                      - width : nil
                      ▿ height : Optional<CGFloat>
                        - some : 10.0
                      ▿ alignment : Alignment
                        ▿ horizontal : HorizontalAlignment
                          ▿ key : AlignmentKey
                            - bits : 140735363993224
                        ▿ vertical : VerticalAlignment
                          ▿ key : AlignmentKey
                            - bits : 140735363993201
            ▿ .3 : Optional<AnyView>
              ▿ some : AnyView
                ▿ storage : <AnyViewStorage<SampleView>: 0x600003e29740>
            ▿ .4 : ModifiedContent<Spacer, _FrameLayout>
              ▿ content : Spacer
                - minLength : nil
              ▿ modifier : _FrameLayout
                - width : nil
                ▿ height : Optional<CGFloat>
                  - some : 55.0
                ▿ alignment : Alignment
                  ▿ horizontal : HorizontalAlignment
                    ▿ key : AlignmentKey
                      - bits : 140735363993224
                  ▿ vertical : VerticalAlignment
                    ▿ key : AlignmentKey
                      - bits : 140735363993201
    - modifiers : 0 elements

so how do I access the tuple at vStack index 1? and 2?

(lldb) po view.vStack().anyView(1)
▿ Unable to extract AnyView: please specify its index inside parent view
  - notSupported : "Unable to extract AnyView: please specify its index inside parent view"

**Comment by nalexn** [comment]
For future reference: this has been addressed in #56, while `.viewBuilder()` will be deprecated in the coming version
