### ISSUE TITLE
Receiving "does not have 'onChange' modifier" after updating to onChange(of:, _ action:) from onChange(of:, perform:)

### ISSUE THREAD

**Issue by Rob-2024** [nalexn/ViewInspector#330]
I have updated the existing `onChange(of:, perform:)` which is deprecated in v17  to `onChange(of:, _ action:). Now ViewInspector doesn't recognize callOnChange reporting `"does not have 'onChange' modifier"`. Here is an example of the error. How can I get these tests working again?

`
    func testOnCall() throws {
        struct TestView: View {
            @State var inputValue: String = ""
            @State var displayValue: String = ""
            var body: some View {
                VStack {
                    Text(displayValue)
                    TextField("Test Input", text: $inputValue)
                }
                .onChange(of: inputValue, { old, new in
                    displayValue = "Was \(old.count > 0 ? old : "N/A") and now is \(new.count > 0 ? new : "N/A")"
                })
            }
        }
        
        let test = TestView()
        XCTAssertNoThrow(try test.inspect().callOnChange(newValue: "Bob"))
        XCTAssertNoThrow(try test.inspect().vStack().callOnChange(newValue: "Bob"))
        XCTAssertNoThrow(try test.inspect().find(ViewType.VStack.self).callOnChange(newValue: "Bob"))
    }
`

**Comment by andy-vanwagoner-jn** [comment]
I added support for the new modifier with `.callOnChange(oldValue:newValue:)`. I don't think there has been a release, so you may need to point to a branch or a commit after the feature was added.

**Comment by nalexn** [comment]
Released with v0.10.0
