### ISSUE TITLE
ButtonStyle .inspect(isPressed: Bool) is failing on Xcode 16

### ISSUE THREAD

**Issue by FelipeDocil** [nalexn/ViewInspector#331]
Trying to run the same code as in the documentation 

```
struct CustomButtonStyle: ButtonStyle {

        public func makeBody(configuration: CustomButtonStyle.Configuration) -> some View {
            configuration.label
                .blur(radius: configuration.isPressed ? 5 : 0)
        }
    }

    func testCustomButtonStyle() throws {
        let sut = CustomButtonStyle()
        XCTAssertEqual(try sut.inspect(isPressed: false).blur().radius, 0)
        XCTAssertEqual(try sut.inspect(isPressed: true).blur().radius, 5)
    }
```

Will give the error `XCTAssertEqual failed: threw error "AnyView does not have 'blur' modifier"`

I know AnyView is a problem with Xcode 16, but I don't know the approach here

**Comment by nalexn** [comment]
Try `XCTAssertEqual(try sut.inspect(isPressed: false).implicitAnyView().blur().radius, 0)`

**Comment by FelipeDocil** [comment]
Same error

`XCTAssertEqual failed: threw error "AnyView does not have 'blur' modifier"`

**Comment by nalexn** [comment]
Ok, that should be `XCTAssertEqual(try sut.inspect(isPressed: false).implicitAnyView().styleConfigurationLabel().blur().radius, 0)`

**Comment by FelipeDocil** [comment]
It did work, thank you
