### ISSUE TITLE
Xcode 16 Beta 6 - Button.tap() fails

### ISSUE THREAD

**Issue by tatsuki-nakano-simplisafe** [nalexn/ViewInspector#332]
Button.tap() fails due to type mismatch of ButtonAction.
Old signature of Button action was `() -> Void` and and new one is `@MainActor () -> Void`.

Here is thrown exception
(lldb) po InspectionError.typeMismatch(value, T.self)
▿ Type mismatch: @MainActor () -> () is not () -> ()
  ▿ typeMismatch : 2 elements
    - factual : "@MainActor () -> ()"
    - expected : "() -> ()"

**Comment by nalexn** [comment]
A duplicate of #318, pending release. You can pin to 0.10.0 branch for now

**Comment by tatsuki-nakano-simplisafe** [comment]
Ah, sorry.  I should have checked carefully.
