### ISSUE TITLE
0.10.0 fails builds with assumeIsolated(_:file:line:)' is only available in iOS 17.0 or newer error

### ISSUE THREAD

**Issue by NishanthReddyKuninti** [nalexn/ViewInspector#333]
- ERROR | [iOS] xcodebuild:  ViewInspector/Sources/ViewInspector/SwiftUI/CustomView.swift:162:30: error: 'assumeIsolated(_:file:line:)' is only available in iOS 17.0 or newer

**Comment by manishkumar03** [comment]
Getting the same error.

❌ /Users/jenkins/builds-runner-8/_work/iOS/iOS/acv-ios-unit-test-dd/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/SwiftUI/CustomView.swift:153:30: 'assumeIsolated(_:file:line:)' is only available in iOS 17.0 or newer
        return try MainActor.assumeIsolated {

**Comment by nalexn** [comment]
Which Xcode are you using?

For Xcode 16 it is defined like that:

```swift
@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    public static func assumeIsolated<T>(_ operation: @MainActor () throws -> T, file: StaticString = #fileID, line: UInt = #line) rethrows -> T where T : Sendable
```

**Comment by liambrozik** [comment]
Getting the same issue on XCode 15.2 in Azure pipelines

**Comment by nalexn** [comment]
Well, I guess you need to either use a newer Xcode (15.4 might work), as there is no way to avoid `assumeIsolated` and support newest features

**Comment by liambrozik** [comment]
Xcode 15.4 did work

**Comment by fangmobile** [comment]
Confirming changing to 15.4 works for me.
