### ISSUE TITLE
Inspecting modifiers fails in Xcode 16

### ISSUE THREAD

**Issue by KonDouvris** [nalexn/ViewInspector#335]
I have the following code.        
        
        XCTAssertEqual(
            try extractButtonBorderDetails(
                from: view
                    .inspect()
                    .implicitAnyView()
                    .modifier(ButtonBorderModifier.self)
            )
            .color,
            color
        )

The test fails with error
`XCTAssertEqual failed: threw error "AnyView does not have 'ButtonBorderModifier' modifier"`

Any help would be appreciated.

I am using Xcode 16.0 and MacOS Sequoia 15.0

**Comment by nalexn** [comment]
Please post the structure of the sut view

**Comment by nalexn** [comment]
If that's a button style, [check out this](https://github.com/nalexn/ViewInspector/issues/331#issuecomment-2343486759)

**Comment by KonDouvris** [comment]
@nalexn Hi!
I've already seen it, but it does not work for my case, unfortunately.
Any other ideas?

**Comment by KonDouvris** [comment]
My sut is the following:

```
let view = EmptyView()
            .buttonBorder(ButtonBorderConfiguration(color: color,
                                                    lineWidth: lineWidth,
                                                    cornerRadius: cornerRadius))
                                                    


struct ButtonBorderModifier: ViewModifier {
    let color: Color
    let cornerRadius: CGFloat
    let lineWidth: CGFloat

    func body(content: Content) -> some View {
        content.overlay(
            RoundedRectangle(cornerRadius: cornerRadius)
                .stroke(color, lineWidth: lineWidth)
        )
    }
}

extension View {
    @ViewBuilder
    func buttonBorder(_ config: ButtonBorderConfiguration?) -> some View {
        if let config {
            modifier(ButtonBorderModifier(color: config.color,
                                          cornerRadius: config.cornerRadius,
                                          lineWidth: config.lineWidth))
        } else {
            self
        }
    }
}
```

**Comment by nalexn** [comment]
```swift
view
            .inspect()
            .implicitAnyView()
            .emptyView()
            .modifier(ButtonBorderModifier.self)
```

should work in this case

**Comment by KonDouvris** [comment]
@nalexn Ok this works! Thanks a lot.

What do we learn from this? I mean, what was the problem and the solution, so we can apply the same principles in other possible scenarios?

**Comment by nalexn** [comment]
The problem is the new compiler in Xcode 16 that messes up with the view hierarchy. There is no common pattern as to when and how it changes the original hierarchy.
Solution - use `find(...)` instead of absolute paths
