### ISSUE TITLE
Build failure: unable to type-check in reasonable time | Xcode 16.0 | 0.10.0

### ISSUE THREAD

**Issue by aleksaspasic** [nalexn/ViewInspector#339]
This issue was present on Xcode 16.0 Beta, according to this issue: https://github.com/nalexn/ViewInspector/issues/307

But it seems that it's still present, but now in release version 16.0 for Xcode. I'm also currently using Sequoia 15.0 version for Macbook.

<img width="670" alt="image" src="https://github.com/user-attachments/assets/8c07ba7e-d13b-45b5-816a-4360ae7dcf77">
<img width="825" alt="image" src="https://github.com/user-attachments/assets/051f3c6f-0ec3-444d-91ba-2d474e853109">

**Comment by nalexn** [comment]
You need to update the library to v0.10.0

**Comment by aleksaspasic** [comment]
@nalexn I am using library v0.10.0
<img width="269" alt="image" src="https://github.com/user-attachments/assets/b25f0096-29b3-4518-aa95-463f167ea255">

**Comment by nalexn** [comment]
Maybe your cache is stale, that [code was reworked](https://github.com/nalexn/ViewInspector/blob/0.10.1/Sources/ViewInspector/ViewSearchIndex.swift#L458).
