### ISSUE TITLE
Missing support for inspecting concatenated Text views

### ISSUE THREAD

**Issue by vruzeda** [nalexn/ViewInspector#34]
I have a use case in which I need to concatenate `Text` views, and I want to inspect the result of that, but ViewInspector throws an error in that case. You can see a really simple example reproducing the issue below:

<table>
<tr>
<th>Test</th>
<th>Result</th>
</tr>

<tr>
<td>
<pre>
    func testSingleText() throws {
        let sut = Text("ab")
        let text = try sut.inspect().text().string()
        XCTAssertEqual("ab", text)
    }
</pre>
</td>
<td>
<pre>
Test Case '-[TargetTests.SwiftUIViewInspectorTests testSingleText]' started.
Test Case '-[TargetTests.SwiftUIViewInspectorTests testSingleText]' passed (0.007 seconds).
</pre>
</td>
</tr>

<tr>
<td>
<pre>
    func testConcatenatedText() throws {
        let sut = Text("a") + Text("b")
        let text = try sut.inspect().text().string()
        XCTAssertEqual("ab", text)
    }
</pre>
</td>
<td>
<pre>
Test Case '-[TargetTests.SwiftUIViewInspectorTests testConcatenatedText]' started.
/path/to/project/Pods/ViewInspector/Sources/ViewInspector/Inspector.swift:17: error: -[TargetTests.SwiftUIViewInspectorTests testConcatenatedText] : failed: caught error: "attributeNotFound(label: "key", type: "ConcatenatedTextStorage")"
Test Case '-[TargetTests.SwiftUIViewInspectorTests testConcatenatedText]' failed (0.322 seconds).
</pre>
</td>
</tr>
</table>

**Test details:**
ViewInspector version: 0.3.8 (installed with Cocoapods)
Cocoapods version: 1.6.1
Swift version: 5
Xcode version: 11.5 (11E608c)
macOS version: 10.15.6

**Comment by nalexn** [comment]
Hey @vruzeda 

Good catch, I didn't know `Text` views can be combined this way . I'll add support for this shortly. A heads up though: I didn't announce integration through cocoapods, so it's unofficial, and currently there is a [blocker](https://github.com/nalexn/ViewInspector/pull/8#issuecomment-647178363) for updating the lib version on the cocoapods. v0.3.8 is [already quite far behind](https://github.com/nalexn/ViewInspector/tags)

**Comment by vruzeda** [comment]
> Hey @vruzeda
> 
> Good catch, I didn't know `Text` views can be combined this way . I'll add support for this shortly. A heads up though: I didn't announce integration through cocoapods, so it's unofficial, and currently there is a [blocker](https://github.com/nalexn/ViewInspector/pull/8#issuecomment-647178363) for updating the lib version on the cocoapods. v0.3.8 is [already quite far behind](https://github.com/nalexn/ViewInspector/tags)

Thanks for the quick reply.

I'll try to persuade the team to start using Swift Package Manager, but we have a legacy project with tons of Cocoapods dependencies, so the easiest way for me to get approval on new dependencies is through the same dependency mechanism. That being said, I'm able to reference the project from GitHub and get version 0.4.0.

**Comment by nalexn** [comment]
v0.4.1 - added support for concatenated Text views

**Comment by vruzeda** [comment]
Works like a charm! Thanks for the lighting fast fix!
