### ISSUE TITLE
Call to main actor-isolated instance method 'inspect(after:function:file:line:_:)' in a synchronous nonisolated context

### ISSUE THREAD

**Issue by rishipandey** [nalexn/ViewInspector#344]
While using the API:
```
view.inspection.inspect { view in
    // Code interacting with the view  
}
```

I encountered the following error:
`Call to main actor-isolated instance method 'inspect(after:function:file:line:_:)' in a synchronous nonisolated context
`
This issue seems to arise due to the synchronous call being made to an actor-isolated method.

**Comment by nalexn** [comment]
Just add `@MainActor` above your test class definition
