### ISSUE TITLE
Is there a reason why the find methods are not marked with discardableResult?

### ISSUE THREAD

**Issue by JOyo246** [nalexn/ViewInspector#349]
A decent bit of our VI tests are checking "does this view exist".

For example, set the correct state for a nav link or sheet to fire, find the nav link, make sure it's presenting MyView.self.

Our tests then are often discarding the result:
`_ = try sut.inspect(findByAID: "").navigationLink().find(MyView.self)`

This isn't exactly obvious that what we are doing is ensuring the view exists, and we're curious if there's a more precise way to write this test, so that it's a bit more obvious as to what it's doing.

Our two ideas include:
- opening a PR to mark all of the find methods as `@discardableResult`, so that there are not warnings that you are not using the output of finding a view. (wanted to ask before opening the PR and it getting shutdown 😅 )
- Add some .exists() method on InspectableView. That way silencing the warning is changed to adding ".exists()" at the end of your expression, to be precise as to why you're ignore the output.

**Comment by nalexn** [comment]
How about using `XCTAssertNoThrow(try view.inspect()...)`

**Comment by JOyo246** [comment]
ah yeah, that would be our third option. Still feels a tad verbose, and we'd probably extend with .exists(), before wrapping in XCT.

is there a particular reason why discardableResult is not used? 🤷

**Comment by nalexn** [comment]
In this regard `find` isn't different from a specific view unwrap calls, like `anyView()`, as both expect you might want to continue chaining with another unwrap call or retrieve an attribute on a view. If we add `discardableResult` to find then it'd be logical to add it to all the unwrap view calls, which doesn't seem right. I think if this really bothers you `.exists()` makes the most sense, as it also explicitly states the intent in tests

**Comment by nalexn** [comment]
And you can add `exists` in your own extension for `InspectableView`, no need for a PR

**Comment by JOyo246** [comment]
Thanks, @nalexn! Closing this!
