### ISSUE TITLE
async inspect() deadlock bug

### ISSUE THREAD

**Issue by nh7a** [nalexn/ViewInspector#352]
Started using the async version of `inspect()` more and more, we realized that tests became very flaky, and it started frequently failing in our CI/CD environment. Investigating the cause, it turned out that the current version of async `inspect()` can deadlock. So, we’re currently adding an artificial delay to all of our uses, like `inspect(after: .seconds(0.1))`. Otherwise, some tests randomly but frequently fail in a CI/CD environment.

#351 is my attempt to fix the bug.

**Comment by nalexn** [comment]
Published with 0.10.1
