### ISSUE TITLE
Question: How to test environment-set state?

### ISSUE THREAD

**Issue by jonreid** [nalexn/ViewInspector#359]
Alexey, sorry to trouble you again. I have a situation and have created a minimal repro here: https://github.com/jonreid/EnableDemo

I want a custom button to change its color depending on whether it's enabled or disabled via `@Environment(\.isEnabled)`.

[The code](https://github.com/jonreid/EnableDemo/blob/main/EnableDemo/ContentView.swift) works when I run it.

[The tests](https://github.com/jonreid/EnableDemo/blob/main/EnableDemoTests/ContentViewTests.swift) for disabled/enabled state work, from toggling a switch.

But `test_customButtonDisabledColor` fails, the test for the color of the disabled state. What trick am I missing?

Thanks in advance… Jon

**Comment by nalexn** [comment]
Hey, that might be caused by #131

**Comment by jonreid** [comment]
Ahhh, is this because it's not arbitrary `@Environment` we control, but there is hidden Apple code setting it that we can't trigger?
