### ISSUE TITLE
Fatal error: No ObservableObject of type [type] found.

### ISSUE THREAD

**Issue by shayna34** [nalexn/ViewInspector#4]
I'm running into some problems inspecting views with `@EnvironmentObject`. Namely, my tests crash with the following error:

**Fatal error: No ObservableObject of type Validation found.
A View.environmentObject(_:) for Validation may be missing as an ancestor of this view.**

I have a Validation class defined as:
```
class Validation: ObservableObject {

    @Published var email = "" {
        didSet {
            self.validateEmail()
        }
    }
    @Published var password = "" {
        didSet {
            self.validatePassword()
        }
    }

    @Published var isValidEmail = false
    @Published var isValidPassword = false

    func validateEmail() {
        // code
    }

    func validatePassword() {
        // code
    }
}
```

The Validation class is used in a view as such:
```
struct LoginView: View {
    
    @EnvironmentObject var validation: Validation

    var body: some View {
        body(validation)
    }

    func body(_ validation: Validation) -> some View {
        // SwiftUI code
    }
}
```

The following test case crashes with the above error (I'm using Nimble/Quick instead of XCTest):
```
describe("LoginView") {
    it("should prompt the user for their email") {
        do {
            let validation = Validation()
            let loginView = LoginView()
            let prompt = try loginView.inspect(validation).zStack().vStack(1).vStack(0).text(0).string()
            expect(prompt).to(equal("What's your e-mail address?"))
        } catch {
            fail("failure - \(error)")
        }
    }
}
```

Is there something that I've missed that would be causing the crash? Any help on this is much appreciated.

**Comment by nalexn** [comment]
This is the error from SwiftUI that indicates that you're accessing somewhere view's `var validation: Validation` instead of the parameter of the  `func body(_ validation: Validation)`. See if you're referring to it as `self.validation`.

**Comment by shayna34** [comment]
Ah, I see the problem. I had this text field:
```
TextField("you@email.com", $validation.email)
```
It turned out `$validation` was referring to `var validation: Validation` instead of the parameter of the `func body(_ validation: Validation)`. I was able to fix it by adding a `@State var email` and refactoring the text field to the following:
```
TextField("you@email.com", $email, onEditingChanged: { _ in
    validation.email = self.email
})
```
Thanks for your help!
