### ISSUE TITLE
forEach on forEach, index out of bounds

### ISSUE THREAD

**Issue by Roman500px** [nalexn/ViewInspector#40]
Hi Alex, thanks for building an awesome library!

There seems to be something wrong going on with the Iterators.
This snippet causes an index out of range exception:
```
let sut = ForEach([0, 1], id:\.self) { id in
    Text("\(id)")
}
        
try sut.inspect().forEach().forEach {
    print($0)
}
```

**Comment by nalexn** [comment]
You're right, just pushed a fix for it. v0.4.5

**Comment by Roman500px** [comment]
It works! Thank you!
