### ISSUE TITLE
Carthage support 

### ISSUE THREAD

**Issue by matiasvillaverde** [nalexn/ViewInspector#45]
We are thinking to start using library for new SwiftUI features, but we need Carthage support because we can not use Swift Package Manager yet. Would it be possible to support it?

**Comment by nalexn** [comment]
Looking into it

**Comment by nalexn** [comment]
@matiasvillaverde 

The framework now should compile with Carthage:

```
github "nalexn/ViewInspector"
```

**Comment by matiasvillaverde** [comment]
Thanks @nalexn! That was fast!
