### ISSUE TITLE
Error while running app

### ISSUE THREAD

**Issue by Ganyev** [nalexn/ViewInspector#49]
Hello, 
I have some unclear issue.

When I run app, it's crashes and in logs I found here:

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/1323FEEC-8B65-43C1-9EA5-8E09E6242D36/data/Containers/Bundle/Application/CAA0CC5F-F5E4-48AA-A0D2-92DF04533468/Xxx.app/Xxx
  Reason: image not found

And it's happening when I add `pod 'ViewInspector'` in Podfile.
If I remove `pod 'ViewInspector'` after pod installing, run app - it's OK.
With other pods app runs also ok.

**Comment by nalexn** [comment]
Hey @Ganyev 

Make sure you add `pod 'ViewInspector'` for the test target, not the main one

**Comment by Ganyev** [comment]
Yes, my fault, I'd added it in main target.
Now, I moved it in test target and I try to inherit my View from `Inspectable` protocol.
When I add `import ViewInspector` there, an error appears `No such module 'ViewInspector'`
What's wrong now?

**Comment by nalexn** [comment]
Check out #22

**Comment by Ganyev** [comment]
@nalexn thanks, I got my problem.
