### ISSUE TITLE
How can I test to present modal?

### ISSUE THREAD

**Issue by theMistletoe** [nalexn/ViewInspector#51]
I wanna test that modal presentation by tapping button. (Like below code)
using ViewInspector, How can i write test code?

```swift
struct ContentView: View {
    @State var isActiveSubView = false

    var body: some View {
        NavigationView {
            VStack {
                 Button(action: {
                     self.isActiveSubView.toggle()
                 }) {
                     Text("Show Modal")
                 }.sheet(isPresented: $isActiveSubView) {
                     SubView()
                 }
            }
        }
    }
}
```

**Comment by nalexn** [comment]
Hey, the library is [currently unable](https://github.com/nalexn/ViewInspector/blob/master/readiness.md#presenting-sheets) to inspect the `sheet`'s state and content view

**Comment by nalexn** [comment]
The v0.7.6 added support for inspecting `Sheet`. With a [few tweaks to the code](https://github.com/nalexn/ViewInspector/blob/master/guide.md#making-sheet-inspectable), you should be able to access the `Sheet`'s content directly as well as using the `find` functions.
