### ISSUE TITLE
Could not install on Xcode 12.2 beta

### ISSUE THREAD

**Issue by multitudes** [nalexn/ViewInspector#52]
I am on Xcode 12.2 beta and I could not install the package. After following the steps described in the documentation the "Finish" button did not become highlighted. Is this a known issue?

![Screenshot 2020-10-07 at 16 47 19](https://user-images.githubusercontent.com/29355828/95347260-fe677900-08bc-11eb-98cf-acb7e8817f3c.png)
Thanks

**Comment by nalexn** [comment]
This is a [known issue](https://developer.apple.com/forums/thread/660753) with Xcode 12.2 beta.

**Comment by Alexander-techIOS** [comment]
Just checking in on this. Since Xcode 12.2 is now officially released. I have managed to install ViewInspector into the project. But when running new Unit Test build I get this error:

```
ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'
ld: warning: Could not find or use auto-linked framework 'XCTest'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_XCTestExpectation", referenced from:
      objc-class-ref in ViewInspector.o
  "__swift_FORCE_LOAD_$_XCTestSwiftSupport", referenced from:
      __swift_FORCE_LOAD_$_XCTestSwiftSupport_$_ViewInspector in ViewInspector.o
  "XCTest.XCTFail(_: Swift.String, file: Swift.StaticString, line: Swift.UInt) -> ()", referenced from:
      (extension in ViewInspector):SwiftUI.View.inspect(file: Swift.StaticString, line: Swift.UInt, traverse: (ViewInspector.InspectableView<ViewInspector.ViewType.ClassifiedView>) throws -> ()) -> () in ViewInspector.o
      (extension in ViewInspector):SwiftUI.View< where A: ViewInspector.Inspectable>.inspect(file: Swift.StaticString, line: Swift.UInt, traverse: (ViewInspector.InspectableView<ViewInspector.ViewType.View<A>>) throws -> ()) -> () in ViewInspector.o
      closure #1 (A.V) -> () in (extension in ViewInspector):ViewInspector.InspectionEmissary.(setup in _7842524499E11E7966421A3557BF3F7D)(inspection: (ViewInspector.InspectableView<ViewInspector.ViewType.View<A.V>>) throws -> (), expectation: __C.XCTestExpectation, file: Swift.StaticString, line: Swift.UInt, function: Swift.String) -> () in ViewInspector.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nalexn** [comment]
@Alexander-techIOS I believe this is a different issue, could you check if you linked the library with the test target only, and not with the main target?

**Comment by Alexander-techIOS** [comment]
Thanks for the response. I installed it with spm and then added ViewInspector to each test target build (under Frameworks)

**Comment by Alexander-techIOS** [comment]
Nvm my comment, it's working. Didn't have to manually add ViewInspector to each build target. It's working now

**Comment by nalexn** [comment]
Now many test targets do you have? I can think of multiple test targets if you have UITestCase target (which is useless for SwiftUI as of now), but usually, there are just two: the main build target and the test target. Could you re-assure you haven't checked in the main target.
--
Yep, let me know if it works eventually

**Comment by Alexander-techIOS** [comment]
Sure let me just clean it up a bit

**Comment by Alexander-techIOS** [comment]
Ok so I've cleaned it up a bit. I created a new Test target. Managed to import ViewInspector fine. Then I created a simple test to test that the Tests work.. lol

Then I copied a test from your README (testVStackOfTexts), if I run this test I have a compile error:

```
Undefined symbols for architecture arm64:
  "nominal type descriptor for ViewInspector.ViewType.VStack", referenced from:
      _symbolic _____y_____G 13ViewInspector011InspectableA0V AA0A4TypeV6VStackV in SPilotDeimosTests.o
  "(extension in ViewInspector):SwiftUI.View.inspect() throws -> ViewInspector.InspectableView<ViewInspector.ViewType.ClassifiedView>", referenced from:
      SPilotDeimosTests.SPilotDeimosTests.testExample() throws -> () in SPilotDeimosTests.o
  "(extension in ViewInspector):ViewInspector.InspectableView< where A: ViewInspector.SingleViewContent>.vStack() throws -> ViewInspector.InspectableView<ViewInspector.ViewType.VStack>", referenced from:
      SPilotDeimosTests.SPilotDeimosTests.testExample() throws -> () in SPilotDeimosTests.o
  "nominal type descriptor for ViewInspector.InspectableView", referenced from:
      _symbolic _____y_____G 13ViewInspector011InspectableA0V AA0A4TypeV010ClassifiedA0V in SPilotDeimosTests.o
      _symbolic _____y_____G 13ViewInspector011InspectableA0V AA0A4TypeV6VStackV in SPilotDeimosTests.o
  "(extension in ViewInspector):ViewInspector.InspectableView< where A == ViewInspector.ViewType.Text>.string(locale: Foundation.Locale) throws -> Swift.String", referenced from:
      SPilotDeimosTests.SPilotDeimosTests.testExample() throws -> () in SPilotDeimosTests.o
     (maybe you meant: default argument 0 of (extension in ViewInspector):ViewInspector.InspectableView< where A == ViewInspector.ViewType.Text>.string(locale: Foundation.Locale) throws -> Swift.String)
  "protocol witness table for ViewInspector.ViewType.ClassifiedView : ViewInspector.SingleViewContent in ViewInspector", referenced from:
      SPilotDeimosTests.SPilotDeimosTests.testExample() throws -> () in SPilotDeimosTests.o
  "protocol witness table for ViewInspector.ViewType.VStack : ViewInspector.MultipleViewContent in ViewInspector", referenced from:
      SPilotDeimosTests.SPilotDeimosTests.testExample() throws -> () in SPilotDeimosTests.o
  "nominal type descriptor for ViewInspector.ViewType.ClassifiedView", referenced from:
      _symbolic _____y_____G 13ViewInspector011InspectableA0V AA0A4TypeV010ClassifiedA0V in SPilotDeimosTests.o
  "(extension in ViewInspector):ViewInspector.InspectableView< where A: ViewInspector.MultipleViewContent>.text(Swift.Int) throws -> ViewInspector.InspectableView<ViewInspector.ViewType.Text>", referenced from:
      SPilotDeimosTests.SPilotDeimosTests.testExample() throws -> () in SPilotDeimosTests.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So regarding your earlier question. I have multiple builds for the project one prod, 1 training and 2 development builds.

**Comment by nalexn** [comment]
Again, some sort of linking issue. Try creating a new project and linking ViewInspector with its test target - make sure the simple test passes. Then get back to your setup and try integrating from scratch, making sure there are no signs of ViewInspector left for the build targets, and clear out DerivedData.

**Comment by Alexander-techIOS** [comment]
Yea I'll do that.. ViewInspector went out of scope now.. Xcode...

**Comment by Alexander-techIOS** [comment]
Just for some closure. All is working. Can also access StateObjects, but need to implement didAppear block in the target view, and only Assert in the didAppear block in test target. 

Thanks for this framework! I only have just started digging into it will maybe reach out for more complex tests.
Is there way to take a snapshot of the sut?

**Comment by nalexn** [comment]
By snapshot, do you mean rendering view onto an image? This is not supported directly, but I'd try wrapping sut in `UIViewRepresentable` and calling `drawViewHierarchyInRect(, afterScreenUpdates: true)`

**Comment by Alexander-techIOS** [comment]
Awesome I will try it out
