### ISSUE TITLE
Xcode hangs on same cases.

### ISSUE THREAD

**Issue by agiokas** [nalexn/ViewInspector#53]
I am experiencing strange issue.

Xcode hangs after I run the following "Test"
Version 12.0.1 (12A7300)

```

import SwiftUI

struct ContentView: View {
    @StateObject var vm = ContentVM()

    var body: some View {
        VStack {
            ForEach(vm.items, id: \.self) { title in
                Button(title) {
                    vm.showText = title
                }.padding(.vertical, 5)
            }
        }
    }
}

class ContentVM: ObservableObject {
    @Published var showText: String?

    let items = ["A1", "A2", "A3"]
}


```

```
import XCTest
import ViewInspector
import SwiftUI
@testable import AnotherCheck

extension ContentView: Inspectable {}

class AnotherCheckTests: XCTestCase {

    func testButton() throws {
        let sut = ContentView()
        let k  = try sut.inspect().vStack()
    }

}

```

**Comment by agiokas** [comment]
The issues has something to do with the @StateObject.

**Comment by nalexn** [comment]
@agiokas have you tried [async inspection](https://github.com/nalexn/ViewInspector/blob/master/guide.md#views-using-state-environment-or-environmentobject)? I didn't have time yet to add tests and fully explore **@StateObject**, but from my current understanding it's closer to "@State" than to "@ObservedObject", so I would try the async inspection instead.

**Comment by patrickbdev** [comment]
I was having problems using @StateObject for holding a reference to my ViewModel as well.
Switching to @ObservableObject resolved the issue (as mentioned by @nalexn's guide that @ObservableObject state changes can be observed synchronously).
I found this stackoverflow page useful in understanding the difference between @ObservableObject and @StateObject and as the following user mentioned, as long as a reference is kept to the @ObservableObject, it won't deallocate.
https://stackoverflow.com/a/62555732/4698501

**Comment by nalexn** [comment]
Feel free to reopen the ticket if the suggestion above did not work for you
