### ISSUE TITLE
Live Preview on Device not working

### ISSUE THREAD

**Issue by NeverwinterMoon** [nalexn/ViewInspector#54]
After I'd added ViewInspector, Live Preview on Device stopped working, it seems:

```
linker command failed with exit code 1 (use -v to see invocation)

Build target ViewInspector:
note: Set ENABLE_PREVIEWS=NO because SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'ViewInspector' from project 'Pods')


Link ViewInspector (arm64):
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The regular Live Preview is working fine though

**Comment by nalexn** [comment]
Hey @NeverwinterMoon 
You should not link ViewInspector with your build target, only with the test target.

**Comment by NeverwinterMoon** [comment]
As far as I understand, I am not doing that...

```
  target 'UnitTest' do
    pod 'ViewInspector', '0.4.12'
  end
```

**Comment by nalexn** [comment]
If pods are integrated correctly, they should leave to trace in the main target. Try pod deintegrate - pod install, see what are the leftovers in the main target. It should not know ViewInspector exists

**Comment by nalexn** [comment]
If you are not bound to using cocoapods, I would highly recommend using SPM or Carthage instead

**Comment by NeverwinterMoon** [comment]
Hah, I am still not able to use SPM (I would have loved to though), as I have some dependencies not supporting that yet.

But yeah, did deintegrate/install and I don't see any traces of ViewInspector in the main target, but the Live Preview on Device is still failing...

I've just tried creating a blank project with Cocoapods and just ViewInspector dependency targeting unit tests and it fails the same way.

**Comment by nalexn** [comment]
Gotcha. I'll have a look over the weekend!

**Comment by nalexn** [comment]
@NeverwinterMoon 

You need to add the following to the end of your podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['ViewInspector'].include? target.name
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
  end
end
```

This should solve the actual problem that was printed in the second message. The first message refers to `SWIFT_OPTIMIZATION_LEVEL`, which [also can be tweaked](https://github.com/CocoaPods/CocoaPods/issues/4439) in podfile. However, this was not needed in my test case.

**Comment by NeverwinterMoon** [comment]
Actually, I managed to solve this.

Cocoapods automatically generates the following Podfile structure by default on initialization (I somehow managed not to pay attention to that):
```
target 'MyProject' do
  target 'UnitTest' do
    pod 'ViewInspector', '0.4.12'
  end
end
```

Even with the above, I was not able to see any references to `ViewInspector` in configs (search paths) generated by Cocoapods for the main target. Nonetheless, I had tried moving the 'UnitTest' target pod configuration to the root level of Podfile and it seemed to do the trick:
```
target 'MyProject' do
end

target 'UnitTest' do
  pod 'ViewInspector', '0.4.12'
end
```

**Comment by nalexn** [comment]
I'm glad you got this sorted out!
