### ISSUE TITLE
Type mismatch: PlayerRowView is not HStack || but it is.

### ISSUE THREAD

**Issue by davidakoontz** [nalexn/ViewInspector#57]
I just installed ViewInspector in my project (via SPD) ViewInspector 0.5.1. in XCode 12.1

```
struct PlayerRowView : View {
    var player: Player

    var body: some View {
        HStack() {
            Spacer()
            Text("#\(player.number) ")
            Text(player.name)
            Spacer()
            Text(player.position)
            Spacer()
            Text(player.atBat)
            Spacer()
            BallField()
                .stroke(Color.blue, lineWidth: 1)
                .frame(width: 10, height: 10)
            Spacer()
        }
    }
}
```

my XCTestCase...

```
 func testStringValue() throws { 
        let taylor = Player(name: "Taylor Swift", number: "17", position: "8", atBat: "BB")
        let view = PlayerRowView(player: taylor)
        let hStack = try view.inspect().hStack()
        let value = try hStack.text(2).string() 
        XCTAssertEqual(value, "Taylor Swift")
    }

```

caught error: Type mismatch: PlayerRowView is not HStack

What am I missing about parsing the view hierarchy?

**Comment by davidakoontz** [comment]
OK - resolved my issue - and YES - it was ALL me.

I just finished a TDD course with James Grenning https://wingman-sw.com - and by watching his process very closely and comparing it to mine... well - he moves in tiny steps - verifies that each step compiles/links/works before moving on to the next one.  So I decided to apply that method to my testing of PlayerRowView...

I thought - heck - I've not validated the unit-testing system works - I just assume it SHOULD!  [foreshadow - I will end up with should all over me]

I decided to install the example ContentView example with the classic "Hello World" and see if that test will pass.
So going BACK to the instructions in Guide.... I copied the ContentView:

```
struct ContentView: View {
    var body: some View {
        Text("Hello, world!")
    }
}
```

Then I copied the example UI Test

```
import XCTest
import ViewInspector // 1.
@testable import MyApp

extension ContentView: Inspectable { } // 2.

final class ContentViewTests: XCTestCase {

    func testStringValue() throws { // 3.
        let sut = ContentView()
        let value = try sut.inspect().text().string() // 4.
        XCTAssertEqual(value, "Hello, world!")
    }
}
```

I don't know if you SEE IT... - but I did!  the STEP #2 
**extension ContentView: Inspectable {}**

I'd not written that in my test!  

Reflecting... I want to BLAME the document... it leaves that out of the subsequent example code...  OK fair.  I skipped to them thinking I had all the setup I needed (WRONG).  Could we get a better error message.... I don't know...  could the ViewInspector validate that the test case extends or implements the Inspectable protocol?  Seems like it could - maybe should.

Anyway - JAMES GRENNING FOR THE WIN!!!  To go really really fast - you are going to need to SLOW d..o..w..n.

Thanks James!

**Comment by nalexn** [comment]
Hey David, I did check the podcast you were on and got lots of gotchas where the confusion comes from when using the library (thanks!), so I know there I should put more descriptive error messages. As for the place where you stuck, you almost got it right - for inspecting the `PlayerRowView` inside the `ContentView` you need to use `.view(PlayerRowView .self)` in the chain. You typed `.view()` at some point, and code autocomplete would have helped you if you didn't have `.hStack` or something else in the tail.

**Comment by davidakoontz** [comment]
Thanks for the note Alexey.  I’m writing about my TDD experiences with Swift https://www.theswiftdojo.com/XCTestFramework <https://www.theswiftdojo.com/XCTestFramework> and I’m sure to write more about ViewInspector.

I once worked with 4 team’s doing a VoIP product… short story we developed about 80% of the UI - before we could make a phone call - the teams were mad/confused… the PO was smart - she had us all sit in on the UI validation test with real users… so many of them could NOT find the buy button, or nearly any of the other functions.  We sat behind a one-way mirror glass… screaming at the idiots … click the button…. Pull down the menu…
It was NOT fun… but we learned a lot - redesigned the UI in about 3 weeks.  Then started on the real code.

I admit … I skimmed the Guide… and then dove right in.  

That was stupid!  I forgot the extension step.  Forgot the inspect() method in the view chain… and didn’t know how to call a “custom” view.   All right there in the FINE manual - RTFM.
 

 <https://about.me/davidakoontz?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>


 	
David A Koontz
iPhone: 360-259-8380
about.me/davidakoontz
 <https://about.me/davidakoontz?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

 	
David A Koontz
iPhone: 360-259-8380
about.me/davidakoontz
 <https://about.me/davidakoontz?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>



 <https://about.me/davidakoontz?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
