### ISSUE TITLE
Inspecting Custom UIViewRepresentable UITextField

### ISSUE THREAD

**Issue by Alexander-techIOS** [nalexn/ViewInspector#58]
I would like to find out how to `setInput(:)` for a UIViewRepresentable UITextField, if it's possible? Is there a way for my custom textfield to conform to your TextField ViewType so that `input` and `setInput` is exposed?

EDIT:
I am referencing the custom TextField in this way:
`try view.geometryReader().hStack().view(DropdownUITextField.self, 1).textField()`

I get this error: `Fatal error: body() should not be called on DropdownUITextfield`

**Comment by nalexn** [comment]
@Alexander-techIOS for any `UIViewRepresentable` you can access the underlying UIKit view by calling `.view(DropdownUITextField.self).actualView().uiView()`. After that, you can set the text directly onto it.

**Comment by Alexander-techIOS** [comment]
Awesome thanks! Apologies for the late response.
