### ISSUE TITLE
Is there a way to identify a view of any type in a SwiftUI view hierarchy given some constraint?

### ISSUE THREAD

**Issue by SumoSimo** [nalexn/ViewInspector#64]
Hi there.

So I know there exists a way to inspect the view hierarchy for a particular UI component by specifying the view hierarchy explicitly, such as `try view.inspect().vStack().button(0)`. However, to avoid exposing implementation details of the view hierarchy in my tests, I'd instead like to determine if there exists a UI component within a view hierarchy that matches some constraint.

For example, say there is a landing screen with a view hierarchy that contains a sign-in button along with other UI components. In my test, I'd like to verify that there exists a button with the text, "Sign In," rather than specifying the view hierarchy explicitly and thereby exposing implementation details.

Is there any way to do this? Much appreciated.

**Comment by joemasilotti** [comment]
#37 might be interesting to you!

**Comment by nalexn** [comment]
I have a working prototype of this feature and plan to complete it within 2 weeks, stay tuned!

**Comment by joemasilotti** [comment]
This is great news! I'm in the middle of writing a blog post for Masilotti.com about ViewInspector. Happy to hold off until this is complete.

**Comment by SumoSimo** [comment]
Looking forward to it!

**Comment by cfilipov** [comment]
Just wanted to share another use case where this would be incredibly useful: in an app where you need to use a custom font everywhere this could be used to find instances where the default system font slipped through.

**Comment by nalexn** [comment]
Gentlemen, I created a [discussion](https://github.com/nalexn/ViewInspector/discussions/65) of the API for this feature, you're welcomed to provide your feedback.

**Comment by nalexn** [comment]
Released in v0.6.0
