### ISSUE TITLE
Error while testing a UIViewRepresentable

### ISSUE THREAD

**Issue by arkulpaKonstantin** [nalexn/ViewInspector#79]
Hello everyone,

I encountered some issues the passt days testing a `UIViewRepresentable`.

The `UIViewRepresentable` I tested is a simple wrapper around `UITextField` with support for switching the `isSecureTextEntry` property and is called `SecureToggleTextField`.

The error happened when I want to extract the UIView form the `SecureToggleTextField` via:
```swift
let textField = try sut.uiView()
```
The error message reads: `caught error: "View for SecureToggleTextField is absent"`

I have tested several different configurations:

1. Simply using the the `.uiView()` method
```swift
let isRevealed = Binding<Bool>(wrappedValue: false)
let sut = SecureToggleTextField(isRevealed: isRevealed)
let textField = try sut.uiView()
```
2. First calling `.inspect()` and then `.actualView().uiView()`
```swift
let isRevealed = Binding<Bool>(wrappedValue: false)
let sut = SecureToggleTextField(isRevealed: isRevealed)
let textField = try sut.inspect().actualView().uiView()
```
3. Wrapping the `SecureToggleTextField` in another View and accessing it like so:
```swift
let textField = try sut.inspect().vStack().view(SecureToggleTextField.self, 0).actualView().uiView()
```

All these approaches produce the same error message.

What am I doing wrong?

**Comment by nalexn** [comment]
@arkulpaKonstantin 

SwiftUI does not boot UIKit contents until the view is present on the screen. This means synchronous tests won't work - you need to host the view on screen and use [asynchronous tests](https://github.com/nalexn/ViewInspector/blob/master/guide.md#views-using-observedobject) instead, like [here](https://github.com/nalexn/ViewInspector/blob/3e7d80d5145a69a3b7e43aa102e8e75f58760368/Tests/ViewInspectorTests/ViewHostingTests.swift#L99).

**Comment by nalexn** [comment]
I consider this a resolved issue, feel free to re-open!
