### ISSUE TITLE
`Find` causes @EnvironmentObject crashes

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [nalexn/ViewInspector#87]
If you're using the find functionality so search for something in the view hierarchy *after* something with an environment object thar be crashes. I tried for about 3 hours to dig into this and understand the different between calling `view(Type.self)` (which works) vs `find(Type.self)` but it's honestly gonna take longer to understand all of the inner workings of the library. Here is a test that reproduces my issue:

```swift
// In your view search tests, where you define views:
final class ModelData: ObservableObject {
    var stringProperty = "Model"
}
struct EnvironmentView: View, Inspectable {
    @EnvironmentObject var data: ModelData
    var body: some View {
        Text(data.stringProperty)
   }
}

// Thing that crashes but shouldn't
func testFindPastViewWithEnviornmentObject() throws {
    struct Embedded: View, Inspectable {
        var body: some View {
            Test.EnvironmentView()
            Text("")
        }
    }
    let view = try Embedded().inspect()
    XCTAssertNoThrow(try view.find(ViewType.Text.self))
}

```

**Comment by nalexn** [comment]
This just got fixed as of v0.7.0
