### ISSUE TITLE
Xcode 12.5 Beta 3 | AttributeGraph: cycle detected through attribute XXXXXX

### ISSUE THREAD

**Issue by davdroman** [nalexn/ViewInspector#92]
I'm having a crash in some unit test code I've had in my codebase for many months now. The issue seems to be consistently ocurring in Xcode 12.5 Beta 3, whilst I've never had it happen in Xcode 12.4 and previous versions.

The approach taken for these unit tests is using ViewInspector through the [Approach #2](https://github.com/nalexn/ViewInspector/blob/master/guide.md#approach-2) method (inspecting a view and asserting upon it).

The detailed crash occurs on the `wait(for: [exp], timeout: 0.1)` line with a `Thread 1: EXC_BAD_ACCESS (code=1, address=0x15154db60)` exception. Additionally, I can observe this in the debugger: `=== AttributeGraph: cycle detected through attribute 252048 ===`.

It doesn't occur on every test, but it happens consistently on specific ones and only after a few successful ones have passed. It could of course be a mistake in my implementation but I wanted to raise it here just in case someone else has come across it in 12.5 Beta.

**Comment by davdroman** [comment]
Additional info: seems to be only happening on iOS 14.5 Simulators. Tried on 14.0.1 and everything's fine, which leads me to think it's an issue introduced with some of the changes in the SwiftUI binary bundled into 14.5.

**Comment by nalexn** [comment]
Hey @davdroman is this resolved for you with the release of Xcode 14.5?

**Comment by davdroman** [comment]
Seems like it @nalexn 👍  closing now.
