### ISSUE TITLE
Is it possible to inspect UIAlertControllers/actionSheets?

### ISSUE THREAD

**Issue by haemi** [nalexn/ViewInspector#94]
I would like to test the appearance of an actionsheet after a button tap - but as the corresponding UIAlertController is not part of the view hierarchy, I cannot `find` it... is there a way to inspect it nevertheless?

**Comment by dented42** [comment]
This seems like it might be related to #51?

**Comment by nalexn** [comment]
Thanks for the ticket! The v0.7.6 added support for inspecting `ActionSheet`. With a [few tweaks to the code](https://github.com/nalexn/ViewInspector/blob/master/guide.md#making-actionsheet-inspectable), you should be able to access the ActionSheet's content, including the `title()`, `message()` and `button(_ index: Int)`. `find` functions are now also able to traverse and locate the views inside `ActionSheet`.

For example, the following code locates the button on an ActionSheet and closes it:
```swift
try sut.inspect().find(ViewType.AlertButton.self, containing: "Cancel").tap()
```
