### ISSUE TITLE
How can I find a custom view at a particular index?

### ISSUE THREAD

**Issue by adamzarn** [nalexn/ViewInspector#96]
If I want to verify that there is a `Text` view at the ith position of an `HStack`, I can find it like this:
```
let ithPositionTextView = try view.inspect().hStack().text(i)
```

How can I do this with a custom view? It'd be nice if you could do something like this:
```
let ithPositionCustomView = try view.inspect().hStack().find(CustomView.self).at(i)
```

**Comment by Tyler-Keith-Thompson** [comment]
We ran into this, ideally there'll be a for reals feature added to the library but here's a hack for you in the interum:

```swift
import Foundation
import SwiftUI

@testable import ViewInspector //Unfortunately you have to testably import for this to work

extension InspectableView {
    func find<T>(_ viewType: T.Type,
                 index: UInt,
                 where condition: (InspectableView<T>) throws -> Bool = { _ in true }
    ) throws -> InspectableView<T> where T: KnownViewType {
        var matchedCount = 0
        do {
            let view = try find(where: { view -> Bool in
                guard let typedView = try? view.asInspectableView(ofType: T.self)
                else { return false }
                let matched = (try? condition(typedView)) == true
                defer { if matched { matchedCount += 1 } }
                return matched && matchedCount == index
            })
            return try view.asInspectableView(ofType: T.self)
        } catch {
            throw InspectionError.viewIndexOutOfBounds(index: Int(index), count: matchedCount)
        }
    }

    func find<V>(_ inspectable: V.Type,
                 index: UInt,
                 where condition: (InspectableView<ViewType.View<V>>) throws -> Bool = { _ in true }
    ) throws -> InspectableView<ViewType.View<V>> where V: Inspectable {
        return try find(ViewType.View<V>.self, index: index, where: condition)
    }
}

```

**Comment by nalexn** [comment]
@adamzarn 

Given your example, there is an API for extracting custom view at index:

```swift
let ithPositionCustomView = try view.inspect().hStack().view(CustomView.self, i)
```

The above is for intention to extract "i"-th child of HStack, which has to be `CustomView`.

In @Tyler-Keith-Thompson example, the intent is different: find  "n"-th view of this type in the entire hierarchy.

There is a way to achieve it without the extension, simply use `findAll` and unwrap the view at the given index in the resulting array. A benefit of this approach is that the search is depth-first, so you'll get a more natural ordering.

Let me know if I'm missing something, I'll be happy to extend the APIs as required!

**Comment by nalexn** [comment]
I've extended the `find` API in `0.7.3` to take two additional parameters: `traversal` for toggling between depth-first and breadth-first algorithms, and `skipFound` that allows for skipping a few first matching views before returning the one you need. @adamzarn consider re-opening the issue if that does not help.

**Comment by adamzarn** [comment]
Thanks @nalexn, `.view(CustomView.self, index)` was exactly what I was looking for.
