### ISSUE TITLE
Depth-First Throwing Search

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [nalexn/ViewInspector#98]
Heya, I've got a feature request:

Can we get a `Find` API that does a depth-first search and throws when an index is not there? `FindAll` is a workaround but having an array access fail is not nearly as nice in tests as having an error get thrown, like we do with most of the ViewInspector API

**Comment by Tyler-Keith-Thompson** [comment]
Also note: `findAll` causes crashes with environment objects currently, so it actually isn't a viable option for us.

**Comment by nalexn** [comment]
@Tyler-Keith-Thompson I've extended the `find` API in `0.7.3` to take two additional parameters: `traversal` for toggling between depth-first and breadth-first algorithms, and `skipFound` that allows for skipping a few first matching views before returning the one you need. Let me know if that's what you expected.

**Comment by Tyler-Keith-Thompson** [comment]
CocoaPods still doesn't seem to know the new version got released but I confirmed 0.7.3's API does precisely what I want and the control of depthFirst or breadthFirst is frankly fantastic. Thank you!
